### ISSUE TITLE
[Interview] New Member Bertrand Martin, sentrysoftware

### ISSUE THREAD

**Issue by ursvill** [Green-Software-Foundation/writers#103]
Bertrand Martin
[sentrysoftware.com](https://sentrysoftware.com/)

**Comment by ursvill** [comment]
Bertrand Martin, Founder and CEO of Sentry Software, new General member.

**Comment by NAMRATA-WOKE** [comment]
Bertrand Martin not responded. We will have to push this article out further.

**Comment by ursvill** [comment]
@Jenya-design - can you create the graphic please


![Image](https://github.com/Green-Software-Foundation/writers/assets/114167830/453b1f91-989c-4361-bcc9-18d1292ebf38)

**Comment by Jenya-design** [comment]
Sure @ursvill please let me know my deadline
Thank you

**Comment by Jenya-design** [comment]
@ursvill also please mark the quote for the cover

**Comment by ursvill** [comment]
end of week would be great;

"By fostering collaboration, research, and innovation, we can pave the way for a greener and more sustainable future in software development and consumption."

**Comment by NAMRATA-WOKE** [comment]
@ursvill made a few edits! Ready to go from my end.

**Comment by ursvill** [comment]
I have only just started working on this...

**Comment by NAMRATA-WOKE** [comment]
Oh, never mind!

**Comment by ursvill** [comment]
@NAMRATA-WOKE - content is ready on DATO to be published. Do you want me to get it live on Friday or wait until Monday?
