### ISSUE TITLE
[Article] Uniting for Green Software

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/writers#115]
## Article Details
_Please enter the details here_

**Proposer**:  Namrata Narayan | Communications Lead | @NAMRATA-WOKE 
**Abstract**: Summarizing the June 5 event and Q&A
**Why**: Amplify the "hype" and lively engagement and SOGS
**Audience**: Developers
**Timeline**: June 8

## Important Information
_To be filled out later_

**Author**: @ursvill 
**Other contributors**: (Experts, Reviewers)
**Article Link**: (Link to the doc, must be in our official GSF drive)
**Graphics Link**: (Link to the design assets for this article, must be in our official GSF drive)
**Published Link**: (The link the article was published to for memory)

## Checklist
- [x] Idea discussed and selected for writing. _After checking this box, set Status to "Todo" under "Articles" project_
- [x] Author identified. _After checking this box Assign issue to the Author_
- [x] Scheduled in calendar
- [x] Google doc link created in GSF drive. 
- [x] In progress. _After checking this box, set Status to "In Progress" under "Articles" project_
- [x] Draft created. _After checking this box, set Status to "In Review" under "Articles" project. Assign issue to Reviewer/Author during the back-and-forth_
- [x] Draft reviewed. _After checking this box, set Status to "In Publishing" under "Articles" project. Assign issue to Graphic Designer and add "Graphic Design" to issue's Projects_
- [x] Graphics created. _After checking this box, assign to TBC for approval._
- [x] Approved. _After checking this box, assign to TBC for publishing._
- [x] Published. After checking this box, set Status to "Ready" under "Articles" project. Assign to Marketing and add "D: Marketing" to issue's Projects
- [ ] Shared on socials
- [ ] Shared on newsletter. After checking this box, set Status to "Done" under "Articles" project and close issue.

**Comment by NAMRATA-WOKE** [comment]
@ursvill thank you so much for putting this together so quickly. I've made my edits and looped in @Jenya-design to create necessary image cards. Hopefully we can launch this tomorrow!

I have a way of addressing these questions, but will need to take action on it closer to the end of the month. Will connect with @adamj89!

**Comment by Jenya-design** [comment]
@NAMRATA-WOKE @ursvill please check the article's cover and the social cards attached
cover [on GSF Drive](https://drive.google.com/drive/folders/1UtHP2KuKfh-xin0Uy6vvn_LOX45rFThE?usp=sharing)
social cards[ in Canva](https://www.canva.com/design/DAFlQ2huRnk/6GMhysJ17qAS3B9EJwNhxg/edit?utm_content=DAFlQ2huRnk&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton) 
Let me know if you need any adjustments, I'll be able to apply them in the morning by 9:30am SBT 

![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/ad10354f-37d4-4360-bcd9-46f482823445)


![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/43c92feb-6109-4e29-8cd4-271b3ccedf70)


![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/40dc5de2-f768-4384-bf66-551841a3867e)

**Comment by ursvill** [comment]
@NAMRATA-WOKE @jawache - published!
