### ISSUE TITLE
[Interview] IMDA / Chen Hui New Member

### ISSUE THREAD

**Issue by ursvill** [Green-Software-Foundation/writers#118]
New Member interview

**Comment by ursvill** [comment]
The new member interview is a great way of introducing yourself and your organization to the other GSF members and our subscribers.

**Comment by ursvill** [comment]
should have draft back by mid Jul

**Comment by ursvill** [comment]
cheached out again

**Comment by NAMRATA-WOKE** [comment]
@ursvill what's the latest here? Do we have the questions drafted? Also, can you confirm if you'll be interviewing Charlene? 

Had a conversation with GovTech today and they work closely with IMDA. Ryan will be speaking with Charlene and he wanted some clarity on how we're approaching this article and when it will be published.

**Comment by ursvill** [comment]
@NAMRATA-WOKE - I have received the interview back yesterday and need to review it. I am working on Ausy first (also came in yesterday), so likely this one will be for next week.

**Comment by ursvill** [comment]
@NAMRATA-WOKE - In case you want to review: https://docs.google.com/document/d/1LUi3ppy0g9wdn5QcYjSJ8nsPMx-FS2oU/

**Comment by NAMRATA-WOKE** [comment]
@ursvill  Yes, will review today!

**Comment by NAMRATA-WOKE** [comment]
@NAMRATA-WOKE will review today. @ursvill to contact @Jenya-design once he has the headshot and ask for designed web asset.

**Comment by Jenya-design** [comment]
@ursvill @NAMRATA-WOKE I'm away starting friday (August 18-27), so in case the headshot won't be awailable by noon UK tomorrow, I'm planning prepare the design in canva where you can drop the headshot. Does it work for you?

**Comment by ursvill** [comment]
![Image](https://github.com/Green-Software-Foundation/writers/assets/114167830/05611194-4e70-48dd-a8bc-3a20df0a4424)

**Comment by ursvill** [comment]
@Jenya-design - just received

**Comment by Jenya-design** [comment]
Thank you @ursvill

**Comment by Jenya-design** [comment]
@ursvill please check the update attached and [on Drive](https://drive.google.com/drive/folders/1eh6hN9G3pVgRZHdsB0qIQvc9Lv8gCsar?usp=sharing)

![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/91a9700b-78ba-41a0-a1b1-66c4988b2a5c)

![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/5a543b6b-38c4-4a0b-8bef-9f93c3267b2f)

**Comment by NAMRATA-WOKE** [comment]
@ursvill is waiting on clearance to use the link to the whitepaper.

**Comment by ursvill** [comment]
@Jenya-design - Can you change the quote on the image to the one below please. By the end of week is fine, I have this article in the pipeline for next week now.
"Our mission to make the digital world greener relies on collaboration, not isolation. By forging partnerships with like-minded and committed allies who share our interests, we can collectively design, develop, and deploy digital solutions with a strong focus on sustainability. With the Green Software Foundation and other technology partners, we aim to promote green practices and reach a mutual consensus on methods to measure the environmental impact of our software solutions effectively."

**Comment by Jenya-design** [comment]
@ursvill please check the update attached and [on Drive](https://drive.google.com/drive/folders/1eh6hN9G3pVgRZHdsB0qIQvc9Lv8gCsar?usp=sharing)

![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/022e9673-96fa-4c96-a70c-ede23f66b2b2)

**Comment by ursvill** [comment]
@NAMRATA-WOKE - published

**Comment by NAMRATA-WOKE** [comment]
@ursvill can you replace the subheading with this:

Our mission to make the digital world greener relies on collaboration, not isolation.

Make sure you double check the article once the change has been made and it doesn't include the ** at the end of the text.

Also the very last sentence, next to 'source' should read: 

** Source: [ICT industry to reduce greenhouse gas emissions by 45% by 2030](https://www.itu.int/en/mediacentre/Pages/PR04-2020-ICT-industry-to-reduce-greenhouse-gas-emissions-by-45-percent-by-2030.aspx)

**Comment by ursvill** [comment]
@NAMRATA-WOKE  - I am not making any further changes, unless they are typos. The text that is live has been approved by IMDA.

**Comment by ursvill** [comment]
@NAMRATA-WOKE - did you share this, can I close it?

**Comment by ursvill** [comment]
@NAMRATA-WOKE - can we close it?

**Comment by ursvill** [comment]
@NAMRATA-WOKE - Has this been socialised, can we close?
