### ISSUE TITLE
[Interview] Savannah, Google

### ISSUE THREAD

**Issue by ursvill** [Green-Software-Foundation/writers#125]

**Comment by ursvill** [comment]
Thanks for sharing Urs. I will send over written responses likely early next week and will let you know on publishing date.

Thanks,
Savannah

**Comment by ursvill** [comment]
Hi Urs,
Just wanted to give you the heads up that I'll probably need more time to get the answers back to you - there are a few folks I'm still waiting on responses from internally. I'll try to get something though by the end of next week if that's OK.

**Comment by ursvill** [comment]
https://docs.google.com/document/d/1ib0GGpioHxsfs0YymZPGljL2l_1JAdvh/

**Comment by ursvill** [comment]
![Image](https://github.com/Green-Software-Foundation/writers/assets/114167830/8b4ca7d3-ab01-4e32-b2da-9ff83c8addff)

**Comment by ursvill** [comment]
@NAMRATA-WOKE @jawache  - draft is ready in case you want to do a separate review

needs to go back to Google, once we did our magic!

**Comment by ursvill** [comment]
@Jenya-design - Hi Jenya, can you create the visuals for this new member interview, please.

**Comment by Jenya-design** [comment]
Sure @ursvill

**Comment by Jenya-design** [comment]
Hi @ursvill please check the images attached and [on Drive](https://drive.google.com/drive/folders/1SKihBMf0wJLFtXNzed0UA9Gp-TjhVmi7?usp=sharing)


![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/dc51b3cf-a6f3-4d3a-9c65-7f62b08fb5c8)


![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/e335cdfa-4b74-4c67-a64b-745c8536314d)

**Comment by NAMRATA-WOKE** [comment]
@ursvill finished my edit!

**Comment by ursvill** [comment]
thanks Urs - just shared with our comms folks. Will get back to you with their feedback.
Thanks,
Savannah

**Comment by NAMRATA-WOKE** [comment]
Waiting on Google to provide clearance for the article. Not sure when we will hear back.

**Comment by ursvill** [comment]
review completed, ready to go. asked for preferred publish date.

**Comment by ursvill** [comment]
https://greensoftware.foundation/articles/meet-savannah-goodman-of-google
