### ISSUE TITLE
[Interview] Thomas, Ausy Technologies

### ISSUE THREAD

**Issue by ursvill** [Green-Software-Foundation/writers#126]

**Comment by ursvill** [comment]
Hi Thomas

Wondering if you had a chance to look at the interview questions. If you prefer, we can also schedule a time for an online call and do the interview that way.

Cheers
Urs

**Comment by ursvill** [comment]
![Image](https://github.com/Green-Software-Foundation/writers/assets/114167830/efb941f0-c323-4031-b928-33c56690d884)

**Comment by ursvill** [comment]
https://docs.google.com/document/d/1vW0jtmCsJsLn02eWknH_Juf0p3LGRWv-C_maCliEfBI/

**Comment by ursvill** [comment]
@Jenya-design - can you create an image for this new member interview please. Would love to get this published before Friday.

**Comment by ursvill** [comment]
@NAMRATA-WOKE - here is my draft for this interview

**Comment by Jenya-design** [comment]
@ursvill Please check the images attached and [on Drive](https://drive.google.com/drive/folders/13J_cQUFO8cviHDI3XenqtU_cKfPxefZg?usp=sharing)
Let me know if it needs any adjustments. Thank you

![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/b0faa377-1a47-41de-bcad-257386f139c1)

![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/f163dbcb-f1f7-4783-852e-7e46206c995c)

**Comment by ursvill** [comment]
@NAMRATA-WOKE - I can't figure out how to have a link on an image; left out the sogs image for now

**Comment by ursvill** [comment]
article live:
https://greensoftware.foundation/articles/reducing-ghg-emissions-by-developing-green-software-meet-thomas-frers-ausy-techno
