### ISSUE TITLE
[Interview] UCL

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/writers#129]

**Comment by NAMRATA-WOKE** [comment]
@NAMRATA-WOKE followed up with Sam & Scott to book introductory call and tee-up Urs for an interview article.

**Comment by ursvill** [comment]
UCL is consistently ranked as one of the top ten universities in the world (QS World University Rankings 2010-2022) 

Prof. Dean Mohamedally, Professor in Computer Science specialising in Software Engineering and Industry Projects - http://www0.cs.ucl.ac.uk/staff/D.Mohamedally/

**Comment by ursvill** [comment]
**GSF New Member Interview Questions UCL**

When did you start thinking about software sustainability, and what motivates you most? 
Could you provide some insights into the IT-related programs offered at UCL?
How does sustainability fit within UCL and your programs?  
How are you thinking about setting goals for improving knowledge and fostering a culture of green software development  within UCL? What challenges are you anticipating?
Is UCL drawing inspiration from any other Higher Ed institutions as it starts its green software journey? 
How does UCL hope to engage with the GSF and contribute to the green software movement? Can you highlight any partnerships or collaborations UCL is exploring to support its green software journey?
What role do you envision for student-led initiatives in promoting sustainability within the college's IT and software development community?
Could you share a personal vision or hope you have for the impact that UCL's involvement in the Green Software Foundation will have on the future of sustainable software development, both within the college and beyond?

**Comment by NAMRATA-WOKE** [comment]
@ursvill go ahead and share these questions! Thanks Urs! If you don't mind, refer to the calendar and propose a publishing date.

**Comment by NAMRATA-WOKE** [comment]
@ursvill can you follow-up on this one?

**Comment by ursvill** [comment]
FU email today

**Comment by NAMRATA-WOKE** [comment]
@ursvill can you please share a status update on this piece?

**Comment by ursvill** [comment]
Hi Urs, Lucy in cc will send shortly.
We have our internal article going live shortly too.
Dean

**Comment by ursvill** [comment]
![Prof Dean Mohamedally](https://github.com/Green-Software-Foundation/writers/assets/114167830/bbffe281-f526-40a2-aee7-d0657c0c95b7)

**Comment by ursvill** [comment]
@Jenya-design - Can you create the image, so I can publish mid next week, please

**Comment by Jenya-design** [comment]
Sure @ursvill 
Quote isn't available yet?

**Comment by ursvill** [comment]
@Jenya-design - use this

We are entering a period of education where Large Language Models are everywhere, and students can make use of generative AI. However, there is still the sustainability cost. We need to metricate AI and ML models to understand better how to teach efficiency and code optimizations to our students.

**Comment by ursvill** [comment]
@NAMRATA-WOKE - ready for review: https://docs.google.com/document/d/1hd09bfTfcWBK0NaXRg_3XugPT64UptXx/

**Comment by Jenya-design** [comment]
@ursvill please check the update attached and [on Drive](https://drive.google.com/drive/folders/1FyW48Eh2DsOoU-Ch8V1FIQUOd7Sz3Q9Q?usp=drive_link)

![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/8aceb805-15f0-4a7a-8f89-0477190675b4)

![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/d5cfaa5d-112a-4dc1-b1ce-a5bd487d0f26)

**Comment by ursvill** [comment]
@NAMRATA-WOKE - scheduled for this week; do you want to review? Otherwise, I will send to UCL for approval.

**Comment by NAMRATA-WOKE** [comment]
@ursvill yes need to review! I'll do it today and have it ready before end of day.

**Comment by NAMRATA-WOKE** [comment]
@ursvill done!

**Comment by ursvill** [comment]
@NAMRATA-WOKE - published

https://greensoftware.foundation/articles/using-less-hardware-and-improving-efficiency-meet-prof-dean-mohamedally-of-ucl
