### ISSUE TITLE
[Interview] GovTech

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/writers#130]
Ryan YEO

**Comment by NAMRATA-WOKE** [comment]
@ursvill sent Ryan questions on Aug 7, which he modified. @NAMRATA-WOKE believes he might be waiting for IMDA's interview to get published first to shape his answers. Namrata recommends Urs reach out again since it's been a week.

**Comment by ursvill** [comment]
![Image](https://github.com/Green-Software-Foundation/writers/assets/114167830/c9253799-75b9-4bf7-80ea-7d8328859c0d)

**Comment by ursvill** [comment]
https://docs.google.com/document/d/1_kSpNJdgjkxqIW43H84P6VfLBdu3u9aX

**Comment by ursvill** [comment]
@NAMRATA-WOKE - I am looking at this now

**Comment by ursvill** [comment]
@Jenya-design - can you create the images, publishing likely within 10 days

**Comment by Jenya-design** [comment]
@ursvill please mark the quote that I can use, when the final version is available

**Comment by ursvill** [comment]
@Jenya-design 
"The right ecosystem will consist of strong internal and external partnerships. GovTech fosters a culture of sustainability within the organization such that we integrate sustainability considerations into every area of our work. We strongly believe that regardless of their designations at work, all GovTech employees play an essential role in enabling our sustainability goals."

**Comment by Jenya-design** [comment]
@ursvill please check the update attached and [on Drive](https://drive.google.com/drive/folders/1oy2Tu1roD2Ax1xyB4nYFC4_CkcY5gjdC?usp=sharing)

![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/8155409e-d24e-45f7-a00b-d3b793167beb)


![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/f8ddb045-4077-43a4-8918-eaaa9eaf2f7c)

**Comment by ursvill** [comment]
@NAMRATA-WOKE - published

**Comment by ursvill** [comment]
@Jenya-design - we need to also update the quote here:

"The right ecosystem will consist of strong internal and external partnerships. At GovTech, we are actively working towards fostering a culture of sustainability where every aspect of our work integrates sustainability considerations. We strongly believe that regardless of their designations at work, all GovTech employees play an essential role in enabling our sustainability goals."

**Comment by Jenya-design** [comment]
@ursvill please check the update atteched and [on Drive](https://drive.google.com/drive/folders/1oy2Tu1roD2Ax1xyB4nYFC4_CkcY5gjdC?usp=sharing)

![GeneralMember-Henry-Chang-GovTech_CreenSoftwareFoundation1](https://github.com/Green-Software-Foundation/writers/assets/69306070/43ff8321-21a6-47d0-b1f2-b5fad751c5d2)
