### ISSUE TITLE
[Article] Tackling AI's Environmental Challenge

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/writers#131]
## Article Details
_Please enter the details here_

**Proposer**: Namrata Narayan | Communications Lead | @NAMRATA-WOKE 
**Abstract**: Providing a summary and key highlights from GSF's livestream panel discussion on Responsible AI (scheduled for October 3 or 5 depending on speaker availability) 
**Why**: Raise awareness about the thought leadership shared on the panel and the next steps practitioners can take to ensure their contributions to the design and development of AI solutions and application of AI is carbon-aware and climate-conscious.
**Audience**: Developers, Solution Architects, Engineers 
**Timeline**: October 9-13

## Important Information
_To be filled out later_

**Author**: @ursvill 
**Other contributors**: @NAMRATA-WOKE 
**Article Link**: (Link to the doc, must be in our official GSF drive)
**Graphics Link**: (Link to the design assets for this article, must be in our official GSF drive)
**Published Link**: (The link the article was published to for memory)

## Checklist
- [x] Idea discussed and selected for writing. _After checking this box, set Status to "Todo" under "Articles" project_
- [x] Author identified. _After checking this box Assign issue to the Author_
- [x] Scheduled in calendar
- [x] Google doc link created in GSF drive. 
- [x] In progress. _After checking this box, set Status to "In Progress" under "Articles" project_
- [x] Draft created. _After checking this box, set Status to "In Review" under "Articles" project. Assign issue to Reviewer/Author during the back-and-forth_
- [x] Draft reviewed. _After checking this box, set Status to "In Publishing" under "Articles" project. Assign issue to Graphic Designer and add "Graphic Design" to issue's Projects_
- [x] Graphics created. _After checking this box, assign to TBC for approval._
- [x] Approved. _After checking this box, assign to TBC for publishing._
- [x] Published. After checking this box, set Status to "Ready" under "Articles" project. Assign to Marketing and add "D: Marketing" to issue's Projects
- [ ] Shared on socials
- [ ] Shared on newsletter. After checking this box, set Status to "Done" under "Articles" project and close issue.

**Comment by NAMRATA-WOKE** [comment]
https://docs.google.com/document/d/1VgYC_HCfmOemZZ9KROJKvhAtVP5kleLM9bDvVCHO-JQ/edit?usp=sharing

**Comment by NAMRATA-WOKE** [comment]
https://www.meetup.com/gsf-global/events/295596991/

**Comment by ursvill** [comment]
draft article: https://docs.google.com/document/d/1wtnOUGQgzzc5AskF73v4ZiCWmAiGh8Ui

- Date to be confirmed
- Speakers tbc
- review article

**Comment by NAMRATA-WOKE** [comment]
Looks good! @ursvill 

Date is October 5. Ready for publishing! Do you have an image?

**Comment by ursvill** [comment]
@Jenya-design - we need an image for this article, do you have time today or tomorrow?

**Comment by Jenya-design** [comment]
Hi @ursvill I can send the image tomorrow

**Comment by Jenya-design** [comment]
@ursvill @NAMRATA-WOKE  please review the image attached and [on Drive](https://drive.google.com/file/d/1_igNJgOfzn86wqTXHbWGkZ7HSuADwutu/view?usp=drive_link)

![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/3249f00d-a560-4052-8e13-1f8267dda099)

**Comment by NAMRATA-WOKE** [comment]
@Jenya-design can have a person other than a white man? I want to bring in a bit more diversity into our imagery if possible. A woman of colour would be great!

**Comment by Jenya-design** [comment]
@NAMRATA-WOKE updated, please let me know what you think

![Balancing-Power-and-Responsibility-GreenSoftwareFoundation](https://github.com/Green-Software-Foundation/writers/assets/69306070/4523e1a6-8657-44a1-81b8-1facfa92fe08)

**Comment by ursvill** [comment]
@NAMRATA-WOKE - published
