### ISSUE TITLE
[Article] In case you missed it: recent developments at the GSF

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/writers#132]
## Article Details
_Please enter the details here_

**Proposer**: Namrata Narayan | Comms Lead | @NAMRATA-WOKE)
**Abstract**: A recap of some of the announcements and updates made from May - August 2023
**Why**: Push content to people and make it easier for our community to find information to opportunities and spaces they'd be interested in -- right now if they want to reference Carbon Aware SDK 1.1 for instance, but don't remember the name or repo link, they have to go go digging through social media or our newsletter archive which is not consumer friendly. 
**Audience**: Software developers and designers 
**Timeline**: End of August 2023

## Important Information
_To be filled out later_

**Author**: @ursvill 
**Other contributors**: @NAMRATA-WOKE 
**Article Link**: (Link to the doc, must be in our official GSF drive)
**Graphics Link**: (Link to the design assets for this article, must be in our official GSF drive)
**Published Link**: (The link the article was published to for memory)

## Checklist
- [x] Idea discussed and selected for writing. _After checking this box, set Status to "Todo" under "Articles" project_
- [x] Author identified. _After checking this box Assign issue to the Author_
- [x] Scheduled in calendar
- [x] Google doc link created in GSF drive. 
- [x] In progress. _After checking this box, set Status to "In Progress" under "Articles" project_
- [x] Draft created. _After checking this box, set Status to "In Review" under "Articles" project. Assign issue to Reviewer/Author during the back-and-forth_
- [x] Draft reviewed. _After checking this box, set Status to "In Publishing" under "Articles" project. Assign issue to Graphic Designer and add "Graphic Design" to issue's Projects_
- [x] Graphics created. _After checking this box, assign to TBC for approval._
- [x] Approved. _After checking this box, assign to TBC for publishing._
- [x] Published. After checking this box, set Status to "Ready" under "Articles" project. Assign to Marketing and add "D: Marketing" to issue's Projects
- [ ] Shared on socials
- [ ] Shared on newsletter. After checking this box, set Status to "Done" under "Articles" project and close issue.

**Comment by NAMRATA-WOKE** [comment]
### GSF Projects

[State of Green Software 2023](https://stateof.greensoftware.foundation/) – A first-of-its-kind digital publication that brings global insights and data to the forefront to decarbonize software at scale. This report clearly states [Green Software is vital for a net zero future](https://stateof.greensoftware.foundation/insights/green-software-vital-for-net-zero/) and provides a clear [business case](https://stateof.greensoftware.foundation/insights/green-software-business-case/) to boost the adoption of green software principles, patterns, and investment in green software projects.

[Impact Engine Framework](https://github.com/Green-Software-Foundation/carbon-ql) – A framework practitioners can use to extend and measure software emissions for every runtime environment.

[Real-Time Energy and Carbon Standard for Cloud Providers](https://github.com/orgs/Green-Software-Foundation/discussions/34) – New standard requiring minute-by-minute metrics for energy usage and carbon footprint being shared by all the cloud providers using the same standard set of metrics.

[Carbon Aware SDK](https://github.com/Green-Software-Foundation/carbon-aware-sdk) –The Carbon Aware SDK helps you build carbon-aware software solutions with the intelligence to use the greenest energy sources. Run them at the greenest time, in the greenest locations, or both! Capture consistent telemetry, report on your emissions reduction, and make informed decisions. Carbon Aware SDK v1.1 adds new features, supporting ElectricityMaps as a new data source (both paid and free APIs), and improves quality of usage and stability. The SDK can now also provide a library for DLL import usage to integrate within a project without the need to deploy an API!

### GSF Initiatives

[GSF Discussions](https://github.com/orgs/Green-Software-Foundation/discussions) – GSF Discussions is replacing Slack. This open forum allows GSF members to engage more seamlessly with the Foundation and the broader software sustainability community.  We encourage everyone to [say hi ](https://github.com/orgs/Green-Software-Foundation/discussions/2)👋🏽 , and subscribe to the categories that interest them the most. 

[GSF Wiki](https://greensoftwarefoundation.atlassian.net/l/cp/2JAu6my6) – This onboarding resource offers everything you need to know about the Foundation, participating in projects, and working group discussions. It also provides insights into our decision-making processes and project management. 

[Contributors Writers Program](https://github.com/Green-Software-Foundation/writers) – The foundation invites software developers, designers, and sustainability leaders to share their perspectives on the GSF website to help increase institutional interest and investments in green software projects.

@ursvill

**Comment by ursvill** [comment]
https://docs.google.com/document/d/1nLkJV0zEGJpgUj5rV9CzVaiygXVxXcVH/

**Comment by ursvill** [comment]
@NAMRATA-WOKE - should I go ahead and publish this?

**Comment by NAMRATA-WOKE** [comment]
@ursvill yes, for Tuesday please!

**Comment by Jenya-design** [comment]
@NAMRATA-WOKE @ursvill image for the article attached and [on Drive](https://drive.google.com/file/d/1bgiemHL7DuCiOuZACie7Eopi-cwIDeYi/view?usp=drive_link)
![Green-Software-Foundation-a-summer-of-milestones](https://github.com/Green-Software-Foundation/writers/assets/69306070/47f2e753-b99e-4a26-b535-e16b24bbcf59)
