### ISSUE TITLE
[Article] A proposed name for this article or topics

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/writers#134]
## Article Details
_Please enter the details here_

**Proposer**: Namrata Narayan | Communications Lead | @NAMRATA-WOKE 
**Abstract**: Highlight the new data portal from Electricity Maps (free and open-source) and communicate its importance 
**Why**: Ties into the work we're doing at the GSF and is a resource everyone can access and benefit from to improve their emissions reporting and practices 
**Audience**: Software developers
**Timeline**: August 24 

## Important Information
_To be filled out later_

**Author**: @NAMRATA-WOKE 
**Other contributors**: Celine and Ciril from Electricity Maps and @ursvill 
**Article Link**: https://docs.google.com/document/d/1u51vquIsuQq9QuEENbMnSWhEXoKTvkvuHlrpZGpYbrc/edit
**Graphics Link**: @Jenya-design can you create a graphic for this article? 
**Published Link**: TBC

## Checklist
- [x] Idea discussed and selected for writing. _After checking this box, set Status to "Todo" under "Articles" project_
- [x] Author identified. _After checking this box Assign issue to the Author_
- [x] Scheduled in calendar
- [x] Google doc link created in GSF drive. 
- [x] In progress. _After checking this box, set Status to "In Progress" under "Articles" project_
- [x] Draft created. _After checking this box, set Status to "In Review" under "Articles" project. Assign issue to Reviewer/Author during the back-and-forth_
- [ ] Draft reviewed. _After checking this box, set Status to "In Publishing" under "Articles" project. Assign issue to Graphic Designer and add "Graphic Design" to issue's Projects_
- [ ] Graphics created. _After checking this box, assign to TBC for approval._
- [ ] Approved. _After checking this box, assign to TBC for publishing._
- [ ] Published. After checking this box, set Status to "Ready" under "Articles" project. Assign to Marketing and add "D: Marketing" to issue's Projects
- [ ] Shared on socials
- [ ] Shared on newsletter. After checking this box, set Status to "Done" under "Articles" project and close issue.

**Comment by Jenya-design** [comment]
Hello @NAMRATA-WOKE 
Do you need the image tomorrow (August 24) or the update on August 28 is ok? I'm on vacation till the end of this week

If it's urgent, please reuse some of the existing items
All images for the published articles [here](https://drive.google.com/drive/folders/1YH6oKnnDy6xvsdI9umB01GVXChgqHHJm) 
Image bank with additional images [here](https://drive.google.com/drive/folders/19NlnsyJKM9bm7fCeA03UgS1jkddsahHo) 

Thank you

**Comment by Jenya-design** [comment]
Hello @ursvill  @NAMRATA-WOKE 
Please check the update for the cover attached and [on Drive](https://drive.google.com/file/d/1KjRGmzobii2IX2o0NZa2ejuIi2ggI7bI/view?usp=sharing)
Let me know if you need any adjustments or additional images

![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/ba117068-7388-4709-9090-2ee2c71fe04f)

**Comment by NAMRATA-WOKE** [comment]
This is perfect - thanks @Jenya-design!
