### ISSUE TITLE
[Interview] GS Advocate Series - Pindy

### ISSUE THREAD

**Issue by ursvill** [Green-Software-Foundation/writers#135]
## Article Details
_Please enter the details here_

**Proposer**: (who is proposing this article idea, Name | Affiliation | GitHub Username)
**Abstract**: (50 word summary of the article)
**Why**: (Why is this article an important topic to discuss and how is it related to the work/mission/theory of change of the GSF)
**Audience**: (Which audience is most going to connect to the content in this article)
**Timeline**: (Should this article come out before or after an important date)

## Important Information
_To be filled out later_

**Author**: (Who is assigned to write this article)
**Other contributors**: (Experts, Reviewers)
**Article Link**: (Link to the doc, must be in our official GSF drive)
**Graphics Link**: (Link to the design assets for this article, must be in our official GSF drive)
**Published Link**: (The link the article was published to for memory)

## Checklist
- [x] Idea discussed and selected for writing. _After checking this box, set Status to "Todo" under "Articles" project_
- [x] Author identified. _After checking this box Assign issue to the Author_
- [x] Scheduled in calendar
- [x] Google doc link created in GSF drive. 
- [x] In progress. _After checking this box, set Status to "In Progress" under "Articles" project_
- [x] Draft created. _After checking this box, set Status to "In Review" under "Articles" project. Assign issue to Reviewer/Author during the back-and-forth_
- [x] Draft reviewed. _After checking this box, set Status to "In Publishing" under "Articles" project. Assign issue to Graphic Designer and add "Graphic Design" to issue's Projects_
- [x] Graphics created. _After checking this box, assign to TBC for approval._
- [x] Approved. _After checking this box, assign to TBC for publishing._
- [x] Published. After checking this box, set Status to "Ready" under "Articles" project. Assign to Marketing and add "D: Marketing" to issue's Projects
- [ ] Shared on socials
- [ ] Shared on newsletter. After checking this box, set Status to "Done" under "Articles" project and close issue.

**Comment by ursvill** [comment]
Pindy will respond in Sep

**Comment by ursvill** [comment]
@NAMRATA-WOKE - Here is what I got from Pindy, I only made minimal adjustments, since I generally want to conserve the tone of the interviewee. It's a bit short, but I am ok to publish like this. If you feel it's too short, I can come up with follow up questions. https://docs.google.com/document/d/1GgxPUXwtldL4rCpy3IIb_PaXhE32GxeJ7Ha9O7_ggzM/

**Comment by ursvill** [comment]
@Jenya-design - Jenya, this interview is part of the GSF Champion series, now renamed to Green Software Advocate Series. Can you create an image for mid next week?

**Comment by Jenya-design** [comment]
@ursvill can I have a photo to use for the portrait?
The icon of the series should stay the same or it's better to update it to match new name?
Current icon 

![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/b04a6b30-5335-4d25-abc6-16a6ca67999e)

**Comment by ursvill** [comment]
If you can change it, would be great.

**Comment by ursvill** [comment]
![1516273630407](https://github.com/Green-Software-Foundation/writers/assets/114167830/85c34ed0-3287-452c-bb6a-b11241598283)

**Comment by Jenya-design** [comment]
@ursvill @NAMRATA-WOKE please check the update attached and [on Drive](https://drive.google.com/drive/folders/1L5hgfLktGhQb1dYQ02ceEDc6Myg0BJsI?usp=drive_link)

![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/2874eb71-2546-4024-830f-72014bac51c1)

**Comment by NAMRATA-WOKE** [comment]
@ursvill made some significant edits to improve the quality of writing. Also, the answer to the last question needs some attention. Too vague and confusing in its current form.

**Comment by ursvill** [comment]
@ursvill - 

Notes for future interviews:

We have a new blog series to celebrate the people in the green software space who are doing amazing work, like yourself.
We would love to interview you, write a piece for our website and share it with our network.

The Green Software Advocate Series is reserved for the top leaders in the field of green software. We established the format to give you platform for expressing the views most dear to you. We also want to celebrate you, and all that you do for the GSF and green software. As such, participation in the GS Advocate Series is a privilege for a handful of carefully selected individuals.

I was envisioning something along the questions below. If you have something else that you want to share, please don’t hold back! Anything you feel would be valuable to share, bring it on! 

- What inspired you to focus on the intersection of software engineering and environmental sustainability?
- In the last 5 years, has there been any particular initiative or project that you felt was truly catalytic in advancing a green transition in software? 
- What advice would you give to software engineers who are passionate about building green software?
- How do you balance your role with your commitment to climate activism in the tech industry?
- How do you see collaboration and partnerships shaping the future of green software and a more sustainable tech culture?
- Which part of green software are you most passionate about?
- Where will you focus most of your energy in the next 2 years?

**Comment by NAMRATA-WOKE** [comment]
https://greensoftware.foundation/articles/green-software-advocate-series-an-interview-with-pindy-bhullar
