### ISSUE TITLE
[Article] Expanding the Toolkit for making software greener with Electricity Maps

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/writers#137]
## Article Details
_Please enter the details here_

**Proposer**: Namrata Narayan | Comms Lead | @NAMRATA-WOKE 
**Abstract**: Highlighting Electricity Maps' latest open-source data portal that makes historical data of electricity consumption available for the first time to help improve carbon accounting and reduce software's carbon emissions
**Why**: To decarbonize software at scale, simplifying the power system's complexities and ensuring we have accurate data about emissions from the electricity grid is a key step. 
**Audience**: Software engineers and data analysts 
**Timeline**: Aug 25

## Important Information
_To be filled out later_

**Author**: @NAMRATA-WOKE 
**Other contributors**: @ursvill 
**Article Link**: https://docs.google.com/document/d/1u51vquIsuQq9QuEENbMnSWhEXoKTvkvuHlrpZGpYbrc/edit
**Graphics Link**: Namrata to repurpose old assets because Jenya is on vacation 
**Published Link**: 

## Checklist
- [x] Idea discussed and selected for writing. _After checking this box, set Status to "Todo" under "Articles" project_
- [x] Author identified. _After checking this box Assign issue to the Author_
- [x] Scheduled in calendar
- [x] Google doc link created in GSF drive. 
- [x] In progress. _After checking this box, set Status to "In Progress" under "Articles" project_
- [x] Draft created. _After checking this box, set Status to "In Review" under "Articles" project. Assign issue to Reviewer/Author during the back-and-forth_
- [x] Draft reviewed. _After checking this box, set Status to "In Publishing" under "Articles" project. Assign issue to Graphic Designer and add "Graphic Design" to issue's Projects_
- [x] Graphics created. _After checking this box, assign to TBC for approval._
- [x] Approved. _After checking this box, assign to TBC for publishing._
- [x] Published. After checking this box, set Status to "Ready" under "Articles" project. Assign to Marketing and add "D: Marketing" to issue's Projects
- [ ] Shared on socials
- [ ] Shared on newsletter. After checking this box, set Status to "Done" under "Articles" project and close issue.

**Comment by NAMRATA-WOKE** [comment]
Will use this image: https://drive.google.com/drive/folders/19NlnsyJKM9bm7fCeA03UgS1jkddsahHo

**Comment by ursvill** [comment]
@NAMRATA-WOKE - looks like there are 2 issues for this #137 and #134

**Comment by NAMRATA-WOKE** [comment]
@ursvill I accidentally created two. This is the most recent so we'll track the progress of this issue!

**Comment by NAMRATA-WOKE** [comment]
Approved Image:

![Image](https://github.com/Green-Software-Foundation/writers/assets/114516498/dc6419da-4b8b-47b7-9eac-1e80e0eb1418)

**Comment by NAMRATA-WOKE** [comment]
@ursvill will publish this article on Thursday!

**Comment by ursvill** [comment]
@NAMRATA-WOKE - published
