### ISSUE TITLE
[Article] Upcoming Green Software Events 

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/writers#140]
## Article Details
_Please enter the details here_

**Proposer**: Namrata Narayan | Dir. Comms & Member Relations | @NAMRATA-WOKE 
**Abstract**: Highlighting upcoming events on green software/addressing green software 
**Why**: Demonstrating the momentum in shifting culture towards sustainability and encouraging our audience to take advantage of all the different opportunities to learn and improve the way they code, design, monitor and measure. 
**Audience**: Software practitioners, primarily software developers and designers 
**Timeline**: September 2023

## Important Information
_To be filled out later_

**Author**: @ursvill 
**Other contributors**: @NAMRATA-WOKE 
**Article Link**: (Link to the doc, must be in our official GSF drive)
**Graphics Link**: (Link to the design assets for this article, must be in our official GSF drive)
**Published Link**: (The link the article was published to for memory)

## Checklist
- [x] Idea discussed and selected for writing. _After checking this box, set Status to "Todo" under "Articles" project_
- [x] Author identified. _After checking this box Assign issue to the Author_
- [x] Scheduled in calendar
- [x] Google doc link created in GSF drive. 
- [x] In progress. _After checking this box, set Status to "In Progress" under "Articles" project_
- [x] Draft created. _After checking this box, set Status to "In Review" under "Articles" project. Assign issue to Reviewer/Author during the back-and-forth_
- [x] Draft reviewed. _After checking this box, set Status to "In Publishing" under "Articles" project. Assign issue to Graphic Designer and add "Graphic Design" to issue's Projects_
- [x] Graphics created. _After checking this box, assign to TBC for approval._
- [x] Approved. _After checking this box, assign to TBC for publishing._
- [x] Published. After checking this box, set Status to "Ready" under "Articles" project. Assign to Marketing and add "D: Marketing" to issue's Projects
- [ ] Shared on socials
- [ ] Shared on newsletter. After checking this box, set Status to "Done" under "Articles" project and close issue.

**Comment by NAMRATA-WOKE** [comment]
@ursvill can you put something together based on this calendar: https://docs.google.com/spreadsheets/d/1JIfSXcOXkvPXozWEAOowoBjevKpB770l_CFdLikjzNA/edit#gid=0

**Comment by ursvill** [comment]
@NAMRATA-WOKE - draft is here, LMK what you think: https://docs.google.com/document/d/1AaNBH0R9E17qL8XddlcnmX-mkQyZaycI/

**Comment by ursvill** [comment]
@Jenya-design - Can you create an image for this one, mid next week, please.

**Comment by Jenya-design** [comment]
@ursvill @NAMRATA-WOKE please check the update for the cover attached and [on Drive](https://drive.google.com/drive/folders/1a3dmIVWkxkn-Q7YBNokdMaV1yNWC6iw1?usp=sharing)

![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/2f554f44-df73-499a-b63e-44c9afec1b53)

**Comment by ursvill** [comment]
@NAMRATA-WOKE - this is published. Creating tables on DATO is a challenge, at least for me.

**Comment by NAMRATA-WOKE** [comment]
@ursvill the second sentence in the headline needs to be part of the body text:

The software development and design community, particularly, is at a pivotal moment in history. It's a moment where the power of coding can be harnessed with a focus on actively contributing to the planet's sustainability, shaping a digital landscape that champions environmental responsibility above all else.

**Comment by ursvill** [comment]
@NAMRATA-WOKE - can we close it?
