### ISSUE TITLE
[Article] Software Carbon Efficiency Rating  

### ISSUE THREAD

**Issue by ursvill** [Green-Software-Foundation/writers#142]
## Article Details
_Please enter the details here_

**Proposer**: (who is proposing this article idea, Name | Affiliation | GitHub Username)
**Abstract**: (50 word summary of the article)
**Why**: (Why is this article an important topic to discuss and how is it related to the work/mission/theory of change of the GSF)
**Audience**: (Which audience is most going to connect to the content in this article)
**Timeline**: (Should this article come out before or after an important date)

## Important Information
_To be filled out later_

**Author**: (Who is assigned to write this article)
**Other contributors**: (Experts, Reviewers)
**Article Link**: (Link to the doc, must be in our official GSF drive)
**Graphics Link**: (Link to the design assets for this article, must be in our official GSF drive)
**Published Link**: (The link the article was published to for memory)

## Checklist
- [x] Idea discussed and selected for writing. _After checking this box, set Status to "Todo" under "Articles" project_
- [x] Author identified. _After checking this box Assign issue to the Author_
- [x] Scheduled in calendar
- [x] Google doc link created in GSF drive. 
- [x] In progress. _After checking this box, set Status to "In Progress" under "Articles" project_
- [x] Draft created. _After checking this box, set Status to "In Review" under "Articles" project. Assign issue to Reviewer/Author during the back-and-forth_
- [x] Draft reviewed. _After checking this box, set Status to "In Publishing" under "Articles" project. Assign issue to Graphic Designer and add "Graphic Design" to issue's Projects_
- [x] Graphics created. _After checking this box, assign to TBC for approval._
- [x] Approved. _After checking this box, assign to TBC for publishing._
- [x] Published. After checking this box, set Status to "Ready" under "Articles" project. Assign to Marketing and add "D: Marketing" to issue's Projects
- [ ] Shared on socials
- [ ] Shared on newsletter. After checking this box, set Status to "Done" under "Articles" project and close issue.

**Comment by ursvill** [comment]
@mvaltas - Hi Marco, I put my draft for a SCER article on GDrive. Can you have a look and let me know what else we can share. I only had the info from the GH issue.
https://docs.google.com/document/d/1oWT7Ixmbzhm-K6kpWUAvS51mGQ6zcAf2/

**Comment by ursvill** [comment]
FU via email and slack today
Marco doing review

**Comment by ursvill** [comment]
@NAMRATA-WOKE - Do you want to do a review? Marco looked at it already, but open to your changes if any.

**Comment by ursvill** [comment]
Hi @Jenya-design - I will need an image for this, early next week would be great. It's a new GSF project that we're presenting.

**Comment by NAMRATA-WOKE** [comment]
@ursvill will review!

**Comment by Jenya-design** [comment]
@ursvill @NAMRATA-WOKE  please review the cover attached and [on Drive](https://drive.google.com/file/d/1mhD2cA_bzjiMD4mhFnHaTZGPxofYP0Nu/view?usp=sharing)

![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/02850815-4887-4b8c-b11e-39296f0f08ef)

**Comment by NAMRATA-WOKE** [comment]
Looks good! @Jenya-design

**Comment by NAMRATA-WOKE** [comment]
@ursvill I've completed my review.

**Comment by ursvill** [comment]
@NAMRATA-WOKE - published
https://greensoftware.foundation/articles/software-carbon-efficiency-rating-a-consumer-friendly-rating-for-software-carbon

**Comment by ursvill** [comment]
@NAMRATA-WOKE - can we close it?

**Comment by ursvill** [comment]
@NAMRATA-WOKE - Has this been socialised, can we close?

**Comment by NAMRATA-WOKE** [comment]
https://greensoftware.foundation/articles/software-carbon-efficiency-rating-a-consumer-friendly-rating-for-software-carbon
