### ISSUE TITLE
[Article] Meet Steering Committee Member of the Green Software Foundation: Lisa McNally of Thoughtworks

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/writers#144]
## Article Details
_Please enter the details here_

**Proposer**: Namrata Narayan | Dir. Communications & Member Relations | @NAMRATA-WOKE 
**Abstract**: Introduce Lisa to the GSF community by asking her a series of questions to understand her role, experience and views on green software, approach at Thoughtworks and aspirations for the field. 
**Why**: Lisa McNally is now the new organization lead for the GSF at Thoughtworks. Since we profiled Dan and Elise, it's only fair we profile her. Lisa is also the global head of Sustainability, which makes her uniquely positioned to speak to Thoughtworks' digital sustainability mandate and how much it influence / represents their broader sustainability efforts.
**Audience**: Sustainability leaders, tech and ICT consultants 
**Timeline**: Mid-October 

## Important Information
_To be filled out later_

**Author**: @ursvill 
**Other contributors**: @NAMRATA-WOKE 
**Article Link**: (Link to the doc, must be in our official GSF drive)
**Graphics Link**: (Link to the design assets for this article, must be in our official GSF drive)
**Published Link**: (The link the article was published to for memory)

## Checklist
- [x] Idea discussed and selected for writing. _After checking this box, set Status to "Todo" under "Articles" project_
- [x] Author identified. _After checking this box Assign issue to the Author_
- [x] Scheduled in calendar
- [x] Google doc link created in GSF drive. 
- [x] In progress. _After checking this box, set Status to "In Progress" under "Articles" project_
- [x] Draft created. _After checking this box, set Status to "In Review" under "Articles" project. Assign issue to Reviewer/Author during the back-and-forth_
- [x] Draft reviewed. _After checking this box, set Status to "In Publishing" under "Articles" project. Assign issue to Graphic Designer and add "Graphic Design" to issue's Projects_
- [x] Graphics created. _After checking this box, assign to TBC for approval._
- [x] Approved. _After checking this box, assign to TBC for publishing._
- [x] Published. After checking this box, set Status to "Ready" under "Articles" project. Assign to Marketing and add "D: Marketing" to issue's Projects
- [ ] Shared on socials
- [ ] Shared on newsletter. After checking this box, set Status to "Done" under "Articles" project and close issue.

**Comment by ursvill** [comment]
@NAMRATA-WOKE  - The new member interviews are more an organizational intro. I would not start doing them for multiple people of the same company. Can we include her in the GS Advocate Series?

**Comment by NAMRATA-WOKE** [comment]
@ursvill 

I'm not sure she'd be appropriate for that series. Let's do it for new SC members - and she is new because she is taking over for Elise. 

We already have two:

https://greensoftware.foundation/articles/meet-a-steering-committee-member-dan-lewis-toakley 

https://greensoftware.foundation/articles/meet-our-steering-committee-elise-zelechowski

**Comment by ursvill** [comment]
![](https://www.thoughtworks.com/content/dam/thoughtworks/images/photography/thoughtworker-profile/l/pro_lisa_mcnally_2.jpeg)

**Comment by ursvill** [comment]
LI:
As the Head of Cleantech & Sustainability at Thoughtworks, I lead a global team of consultants and technologists who help clients accelerate their transition to a low-carbon and circular economy. With over 20 years of experience in the energy and transportation sectors, I have a passion for creating solutions that address the environmental and social challenges of our time.

**Comment by NAMRATA-WOKE** [comment]
@ursvill remind me, where are we on this?

**Comment by ursvill** [comment]
received some answers but not all of them, asked for more content

**Comment by ursvill** [comment]
@NAMRATA-WOKE - ready for your review
https://docs.google.com/document/d/1E7_k_iWmo0etyMTG3YmL_LwyQSMOovIk/

**Comment by ursvill** [comment]
![Org-Leads-Lisa-McNally-Thoughtworks-01](https://github.com/Green-Software-Foundation/writers/assets/114167830/5e37878c-e179-40d6-889b-b182f875bfe4)

**Comment by ursvill** [comment]
![Org-Leads-Lisa-McNally-Thoughtworks-02](https://github.com/Green-Software-Foundation/writers/assets/114167830/5a9dfab8-fd5f-45b8-b7cc-da0fcb38224f)

**Comment by ursvill** [comment]
@NAMRATA-WOKE - published
https://greensoftware.foundation/articles/open-source-tooling-at-the-core-of-innovation-meet-lisa-mcnally-head-of-sustainab
