### ISSUE TITLE
[Interview] Carolin Rubner, Head of Research Group at Siemens

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/writers#145]
## Important Information

**Author**: @ursvill 
**Other contributors**: @NAMRATA-WOKE 
**Article Link**: (Link to the doc, must be in our official GSF drive)
**Graphics Link**: (Link to the design assets for this article, must be in our official GSF drive)
**Published Link**: (The link the article was published to for memory)

## Checklist
- [x] #146
- [x] Scheduled in calendar
- [x] Google doc link created in GSF drive. 
- [x] In progress. _After checking this box, set Status to "In Progress" under "Articles" project_
- [x] Draft created. _After checking this box, set Status to "In Review" under "Articles" project. Assign issue to Reviewer/Author during the back-and-forth_
- [x] Draft reviewed. _After checking this box, set Status to "In Publishing" under "Articles" project. Assign issue to Graphic Designer and add "Graphic Design" to issue's Projects_
- [x] Graphics created. _After checking this box, assign to TBC for approval._
- [x] Approved. _After checking this box, assign to TBC for publishing._
- [x] Published. After checking this box, set Status to "Ready" under "Articles" project. Assign to Marketing and add "D: Marketing" to issue's Projects
- [x] Shared on socials
- [x] Shared on newsletter. After checking this box, set Status to "Done" under "Articles" project and close issue.

**Comment by NAMRATA-WOKE** [comment]
@ursvill I will make the introduction via email!

**Comment by ursvill** [comment]
Hi Urs,
 sorry for my late feedback. We’re just checking some internal alignments on the Q&A article. I will send it to you asap, until end of this week latest.
 Thanks for your patience and best regards
Caroline

**Comment by NAMRATA-WOKE** [comment]
@ursvill please follow-up on Wednesday if you don't hear back. TY!

**Comment by NAMRATA-WOKE** [comment]
@ursvill to reach out today.

**Comment by ursvill** [comment]
![Carolin](https://github.com/Green-Software-Foundation/writers/assets/114167830/56532452-74d1-47e4-bad5-adfe2470aad0)

**Comment by ursvill** [comment]
https://docs.google.com/document/d/12A7zIVdPmxZst5YbdlzanECLbxrQfV18/

**Comment by ursvill** [comment]
@NAMRATA-WOKE - here is the draft: https://docs.google.com/document/d/12A7zIVdPmxZst5YbdlzanECLbxrQfV18/
Lmk when good to go from your end, so I can ask Siemens to give final approval.

**Comment by ursvill** [comment]
@NAMRATA-WOKE - If you can look at this today, I might still be able to publish this week

**Comment by NAMRATA-WOKE** [comment]
Yes, looking at it today. We already have one scheduled for Tuesday correct? So if this is ready, let's aim for Thursday! @ursvill

**Comment by Jenya-design** [comment]
@ursvill @NAMRATA-WOKE please check the update attached and on [GSF Drive](https://drive.google.com/drive/folders/12fa69cI8v-xfXPFfPqDve6NN7mqEhzdp?usp=drive_link)
There are 2 color options please use one that'll make better contrast with the previous publication
Let me know if you need any adjustments

![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/19df94ce-d77d-4858-9b65-707d84bd6f96)

![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/3c35bb6e-d7a7-41d7-b129-92067d1d8b8e)

![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/cd95cc54-3a77-47ab-ac3c-5e3d77e97897)

**Comment by NAMRATA-WOKE** [comment]
@Jenya-design can you create one with just the Siemens logo that you did for the other Q&As? Thanks!

**Comment by Jenya-design** [comment]
Hi @NAMRATA-WOKE do you mean similar to [this one](https://www.datocms-assets.com/56002/1698876800-siemens-sc-profiles-green-software-foundation.jpg?auto=compress%2Cformat&w=1920)?
This design was previously used for 'new company joins steering committee' occasions. Does that make sense to use the same here? I can remove Carolin's photo from the last image and adjust the composition around Siemens logo if you want to bring more focus on it. What do you think?

**Comment by Jenya-design** [comment]
@ursvill @NAMRATA-WOKE please check the additional options attached and on [GSF Drive](https://drive.google.com/drive/folders/12fa69cI8v-xfXPFfPqDve6NN7mqEhzdp?usp=drive_link)

![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/5b2c68e9-6bbf-4880-8478-5d31889f85a4)

![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/7162048a-128e-4835-995c-f656c3e4fd91)

**Comment by ursvill** [comment]
@NAMRATA-WOKE - this article is live now
