### ISSUE TITLE
[Article] Summary of The Imperative for Sustainable AI Systems article

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/writers#147]
## Article Details
_Please enter the details here_

**Proposer**: Namrata Narayan | Dir. Comms & Member Relations | @NAMRATA-WOKE 
**Abstract**: Proposed by the SWG, this blog would summarize a blog [recently written](https://thegradient.pub/sustainable-ai/) by Abhishek Gupta, Co-chair of the SWG.
**Why**: Draw more visibility to his thought leadership and the importance of factoring in the environmental sustainability of AI when thinking about responsible AI. Aligns with what the Foundation is doing to bring visibility to this issue and the Oct 5 panel. 
**Audience**: Developers 
**Timeline**: October 3

## Important Information
_To be filled out later_

**Author**: (Who is assigned to write this article)
**Other contributors**: @NAMRATA-WOKE 
**Article Link**: (Link to the doc, must be in our official GSF drive)
**Graphics Link**: (Link to the design assets for this article, must be in our official GSF drive)
**Published Link**: (The link the article was published to for memory)

## Checklist
- [x] Idea discussed and selected for writing. _After checking this box, set Status to "Todo" under "Articles" project_
- [x] Author identified. _After checking this box Assign issue to the Author_
- [x] Scheduled in calendar
- [x] Google doc link created in GSF drive. 
- [x] In progress. _After checking this box, set Status to "In Progress" under "Articles" project_
- [x] Draft created. _After checking this box, set Status to "In Review" under "Articles" project. Assign issue to Reviewer/Author during the back-and-forth_
- [x] Draft reviewed. _After checking this box, set Status to "In Publishing" under "Articles" project. Assign issue to Graphic Designer and add "Graphic Design" to issue's Projects_
- [x] Graphics created. _After checking this box, assign to TBC for approval._
- [x] Approved. _After checking this box, assign to TBC for publishing._
- [x] Published. After checking this box, set Status to "Ready" under "Articles" project. Assign to Marketing and add "D: Marketing" to issue's Projects
- [ ] Shared on socials
- [ ] Shared on newsletter. After checking this box, set Status to "Done" under "Articles" project and close issue.

**Comment by ursvill** [comment]
https://docs.google.com/document/d/1BPrIfDKoRE58h2BFfU25XofWALfjUE9c/

**Comment by NAMRATA-WOKE** [comment]
@Jenya-design can you create a graphic for this article please?

**Comment by NAMRATA-WOKE** [comment]
@ursvill made my edits. Requested Jenya above to design an image for the article.

**Comment by ursvill** [comment]
@Jenya-design - Hi Jenya, this one is the first priority. If you can do it on Monday that would be fantastic. We would like to publish on Tue.

**Comment by Jenya-design** [comment]
@ursvill @NAMRATA-WOKE ok, I'll send the update on Monday

**Comment by Jenya-design** [comment]
@NAMRATA-WOKE @ursvill please check the cover image attached and [on Drive](https://drive.google.com/drive/folders/1k-qkhkPDsPoDn7WlyRhFIsw4KYKlarjj?usp=drive_link)

![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/984a0e2c-7e15-4264-b19c-3859824394ef)
