### ISSUE TITLE
[Interview] Mohammad Haque of Indeed

### ISSUE THREAD

**Issue by ursvill** [Green-Software-Foundation/writers#148]
## Article Details
_Please enter the details here_

**Proposer**: (who is proposing this article idea, Name | Affiliation | GitHub Username)
**Abstract**: (50 word summary of the article)
**Why**: (Why is this article an important topic to discuss and how is it related to the work/mission/theory of change of the GSF)
**Audience**: (Which audience is most going to connect to the content in this article)
**Timeline**: (Should this article come out before or after an important date)

## Important Information
_To be filled out later_

**Author**: (Who is assigned to write this article)
**Other contributors**: (Experts, Reviewers)
**Article Link**: (Link to the doc, must be in our official GSF drive)
**Graphics Link**: (Link to the design assets for this article, must be in our official GSF drive)
**Published Link**: (The link the article was published to for memory)

## Checklist
- [x] Idea discussed and selected for writing. _After checking this box, set Status to "Todo" under "Articles" project_
- [x] Author identified. _After checking this box Assign issue to the Author_
- [x] Scheduled in calendar
- [x] Google doc link created in GSF drive. 
- [x] In progress. _After checking this box, set Status to "In Progress" under "Articles" project_
- [x] Draft created. _After checking this box, set Status to "In Review" under "Articles" project. Assign issue to Reviewer/Author during the back-and-forth_
- [x] Draft reviewed. _After checking this box, set Status to "In Publishing" under "Articles" project. Assign issue to Graphic Designer and add "Graphic Design" to issue's Projects_
- [x] Graphics created. _After checking this box, assign to TBC for approval._
- [x] Approved. _After checking this box, assign to TBC for publishing._
- [x] Published. After checking this box, set Status to "Ready" under "Articles" project. Assign to Marketing and add "D: Marketing" to issue's Projects
- [x] Shared on socials
- [x] Shared on newsletter. After checking this box, set Status to "Done" under "Articles" project and close issue.

**Comment by ursvill** [comment]
![Mohammad-Haque-headshot](https://github.com/Green-Software-Foundation/writers/assets/114167830/18fd1a53-9a67-4485-b1ef-1d754301b191)

**Comment by ursvill** [comment]
@NAMRATA-WOKE - https://docs.google.com/document/d/1fUpks-k0XvTRgIODmV2zh0MUK96XDXgY/
ready for edits

**Comment by NAMRATA-WOKE** [comment]
@ursvill edits made. Some comments for you!

**Comment by ursvill** [comment]
Hi Urs,
This is good to go!  Thanks for taking the time!

**Comment by ursvill** [comment]
@Jenya-design - can you create an image.
Quote: “Indeed has set a 2030 net zero emissions goal. Accurately measuring the emissions associated with our use of technology, the cloud, and everything associated with that is the first part. And then, it’s about reducing emissions to hit our goal.”
I would like to publish by Tue next week, if possible.

**Comment by Jenya-design** [comment]
@ursvill please check the images attached and [on Drive](https://drive.google.com/drive/folders/1Bi8vRivAjQD2mTKiTfOnwc8wQGHTSZGo?usp=share_link)
Let me know if you need any adjustments

![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/7e187118-6d0a-435f-8b8b-5909bfe72ad0)

![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/01969094-e590-4be1-9c6e-17d5fd6c6fea)

**Comment by ursvill** [comment]
will publish on Thu Oct 26

**Comment by ursvill** [comment]
@NAMRATA-WOKE - published
