### ISSUE TITLE
Joint Press Release Announcing Siemens as new SC Member

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/writers#149]
NEXT STEPS

- [x] Namrata draft press release
- [x] Namrata share draft with Asim for quote approval
- [x] Namrata share draft with Siemens team for contribution/edits/approval
- [ ] Namrata build press release outreach list on Meltwater 
- [ ] Namrata share press release using Meltwater 
- [x] Namrata share press release with URS to publish 

https://docs.google.com/document/d/1dpb7nmzvjsRNj2iQrSCTfzzYRgzW8t52srfPtaM5a1Y/edit

**Comment by ursvill** [comment]
https://greensoftware.foundation/articles/siemens-joins-green-software-foundation-s-steering-committee-to-drive-sustainable
