### ISSUE TITLE
[Article] Summary of RAI Panel on October 5

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/writers#157]
## Article Details
_Please enter the details here_

**Proposer**: Namrata Narayan | Dir. Communications & Member Relations | @NAMRATA-WOKE 
**Abstract**: Recap of the panel, including key insights and observations and answers to questions
**Why**: To continue the dialogue and build actions around the environmental sustainability of AI
**Audience**: Software Engineers 
**Timeline**:  October 23

## Important Information
_To be filled out later_

**Author**: @ursvill 
**Other contributors**: (Experts, Reviewers)
**Article Link**: (Link to the doc, must be in our official GSF drive)
**Graphics Link**: (Link to the design assets for this article, must be in our official GSF drive)
**Published Link**: (The link the article was published to for memory)

## Checklist
- [x] Idea discussed and selected for writing. _After checking this box, set Status to "Todo" under "Articles" project_
- [x] Author identified. _After checking this box Assign issue to the Author_
- [x] Scheduled in calendar
- [x] Google doc link created in GSF drive. 
- [x] In progress. _After checking this box, set Status to "In Progress" under "Articles" project_
- [x] Draft created. _After checking this box, set Status to "In Review" under "Articles" project. Assign issue to Reviewer/Author during the back-and-forth_
- [x] Draft reviewed. _After checking this box, set Status to "In Publishing" under "Articles" project. Assign issue to Graphic Designer and add "Graphic Design" to issue's Projects_
- [x] Graphics created. _After checking this box, assign to TBC for approval._
- [x] Approved. _After checking this box, assign to TBC for publishing._
- [x] Published. After checking this box, set Status to "Ready" under "Articles" project. Assign to Marketing and add "D: Marketing" to issue's Projects
- [x] Shared on socials
- [x] Shared on newsletter. After checking this box, set Status to "Done" under "Articles" project and close issue.

**Comment by NAMRATA-WOKE** [comment]
Hi @ursvill can you support on this front? It's also been requested by our panelists and SC members.

Panel recording: https://www.youtube.com/watch?v=0CX9J3oAipM

### List of remaining questions (let's talk about how we want to address these!), and some comments:

[YouTube chat CVS
](https://docs.google.com/spreadsheets/d/1jlTHIe5ZlN_fz6l61IZhDPoGiKdXIaov/edit?usp=sharing&ouid=102812099925850911550&rtpof=true&sd=true) (please access using your GSF email)

Mark Butcher: What’s your view on cloud providers like AWS and their “carbon reporting tool”? Do you think customers building AI platforms will be misinformed by that dashboard

Mark Butcher: Will potential fines be enforced and will they be substantial

Mark Butcher: How can companies truly build sustainable AI platforms when none of them understand how to measure emissions?

Ben Gurney: Does the entire paradigm of these model being so power hungry not mean that they are not sustainable in their current form?

Molly Anglin: To Chris and Naveen - both Avanade and Accenture presumably have a strong imperative to sell more consulting services involving AI, Do you bring the environmental considerations into your client conversations consistently? How?

Ben Gurney: Until the models themselves become less power hungry and more efficient to train is there any hope of AI being sustainable?

Atiyah: In terms of quantifiable metrics, how much potential is there if AI is conducted in an environmentally friendly way (from hardware and software perspective) if possible?

Tim Honisett: Are there defined software engineering methods for developing greener software?

Jiri Skopek: How important is the prompt engineering for improvement of AI efficiency?

Jon Clark: Data storage and AI will function as distinct components in this new AI architecture, with data storage handling the storage and retrieval of information while AI processes and analyzes this data to derive insights and make informed decisions. So new designs and optimizations will be required.

Ben Gurney: Can building AI with low energy requirements be a primary goal of the design process for a particular model?

kunalmcitm: How to ensure that implementation of Gen AI, leading to overall savings, does offset the reduction in emissions overall (net emissions). Can you please shed some light on the same?

Oliver Cronk: Isn't a lot of the challenge with AI that we are often solving problems with brute forcing and massive amounts of data and compute (particularly with general / foundational models). Is part of the answer doing the hard work of creating a specific model for the problem you are looking to solve and not reaching for the easy answer?

Houleye SIEGEL, Executive Director at JPMorgan Chase & Co.: I agree with Elif, one way in addition to building carbon aware applications is also to give the transparency to the end user on energy used in function of functionalities used and enable them to adapt their usage (energy efficiency mode,…)based on those metrics, i.e have end user awareness regarding energy consumption.

Oliver Cronk, Tech Director (Sustainable Software) at Scott Logic: Isn't a lot of the challenge with AI that we are often solving problems with brute forcing and massive amounts of data and compute (particularly with general / foundational models). Is part of the answer doing the hard work of creating a specific model for the problem you are looking to solve and not reaching for the easy answer?

Jia Yi Chow, Software Engineer | Ex-PayPal: Software will inherently emit carbon, its all about making it minimal and really use AI sparingly

Raymond du Toit: This groups is seeking make AI a useful tool to address some of the challenges: https://aiforgood.itu.int/

Mathieu Wolff, Consultant Numérique Responsable: What about AI's rebound side-effects ?

Jon Clark, Data Centre Sustainability Lead: Green AI, site and self-generation of power and utilization of heat and also factoring data sovereignty will be key as we move forwards with designs and AI builds. But this is not a quick fix and need a thought-out designs and builds.

Mark Butcher, Digital sustainability & GreenOps advocate: Green AI is not possible. It’s that simple. Just own the impact of your actions and report honestly with transparency

Ben Gurney, Engineering Manager at Container Solutions: Can building AI with low energy requirements be a primary goal of the design process for a particular model?

Mark Butcher: No platform has negative emissions - that is greenwashing pure and simple

Jon Clark, Data Centre Sustainability Lead: Data storage and AI will function as distinct components in this new AI architecture, with data storage handling the storage and retrieval of information while AI processes and analyzes this data to derive insights and make informed decisions. So new designs and optimizations will be required.

Mark Butcher: PUE is not a good metric anymore, it’s abused too much by the data centre industry

Mark Butcher: How do you measure the carbon impact whilst you shift regions? Given the size and cost is that even a practical idea? Nice in concept but not actually realistic at scale.

Mark Butcher: Don’t use queries per Watt, you’ll be missing up to 90% of your emissions and will make incorrect decisions as a result.

Jon Clark: How does the panel look to measure, manage and specifically focus on Scope 3 emissions in the context of AI-driven technologies and data centre operations, and what innovative strategies or technologies are emerging to address these indirect environmental impacts?

Raymond du Toit: Interesting comparison of AI models:
http://ai-carbon-efficiency-observatory.ai-for-sdgs.academy/#emission_chart

Ben Gurney: Until the models themselves become less power hungry and more efficient to train is there any hope of AI being sustainable?

Ben Gurney: Does the entire paradigm of these model being so power hungry not mean that they are not sustainable in their current form?

Mark Butcher: How can companies truly build sustainable AI platforms when none of them understand how to measure emissions?

Mark Butcher: Will potential fines be enforced and will they be substantial

Mark Butcher: What’s your view on cloud providers like AWS and their “carbon reporting tool”? Do you think customers building AI platforms will be misinformed by that dashboard?

**Comment by ursvill** [comment]
@NAMRATA-WOKE - so the goal is a recap of the panel, right? Am I doing anything with these questions above, assume these are just for the WG?

**Comment by NAMRATA-WOKE** [comment]
@ursvill yes, recap. Like we did for the June 5th event. I'll then share it with the panelists for their approval and give them an opportunity to elaborate/clarify any comments/answers they provided, and ask for a quote about how they felt about the event. 

In terms of doing anything with the questions, perhaps mention that the questions we didn't get to, like (x, x) (leave room for me to plug them in later), we plan on addressing in a fireside chat with Jesse during Decarb!

**Comment by ursvill** [comment]
@NAMRATA-WOKE - draft is here: https://docs.google.com/document/d/1KPzQ7pjuy6ZpAP3DGVAsM2epDqc6CJOQ/

**Comment by NAMRATA-WOKE** [comment]
### October 26 Call w/ Bernhard for PR 

- Connections with business reporters (PR not that much of interest)
- Technology list - good amount of reporters 
- Not covering all of Europe/ important tech outlets

**Comment by Jenya-design** [comment]
@ursvill @NAMRATA-WOKE please check the illustration attached and[ on Drive](https://drive.google.com/drive/folders/1Wyv6vYaD58FQZikH7wx4m4lN9NE_vI_B?usp=drive_link)

![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/ce7cf117-1a66-4498-91b4-959326ee9505)

**Comment by NAMRATA-WOKE** [comment]
@Jenya-design thanks!

**Comment by NAMRATA-WOKE** [comment]
@ursvill will you publish this today?

**Comment by ursvill** [comment]
done: https://greensoftware.foundation/articles/can-ai-truly-be-green
