### ISSUE TITLE
[Article] GMT Use Case

### ISSUE THREAD

**Issue by ursvill** [Green-Software-Foundation/writers#158]
## Article Details
_Please enter the details here_

**Proposer**: (who is proposing this article idea, Name | Affiliation | GitHub Username)
**Abstract**: (50 word summary of the article)
**Why**: (Why is this article an important topic to discuss and how is it related to the work/mission/theory of change of the GSF)
**Audience**: (Which audience is most going to connect to the content in this article)
**Timeline**: (Should this article come out before or after an important date)

## Important Information
_To be filled out later_

**Author**: (Who is assigned to write this article)
**Other contributors**: (Experts, Reviewers)
**Article Link**: (Link to the doc, must be in our official GSF drive)
**Graphics Link**: (Link to the design assets for this article, must be in our official GSF drive)
**Published Link**: (The link the article was published to for memory)

## Checklist
- [x] Idea discussed and selected for writing. _After checking this box, set Status to "Todo" under "Articles" project_
- [x] Author identified. _After checking this box Assign issue to the Author_
- [x] Scheduled in calendar
- [x] Google doc link created in GSF drive. 
- [x] In progress. _After checking this box, set Status to "In Progress" under "Articles" project_
- [x] Draft created. _After checking this box, set Status to "In Review" under "Articles" project. Assign issue to Reviewer/Author during the back-and-forth_
- [x] Draft reviewed. _After checking this box, set Status to "In Publishing" under "Articles" project. Assign issue to Graphic Designer and add "Graphic Design" to issue's Projects_
- [x] Graphics created. _After checking this box, assign to TBC for approval._
- [x] Approved. _After checking this box, assign to TBC for publishing._
- [x] Published. After checking this box, set Status to "Ready" under "Articles" project. Assign to Marketing and add "D: Marketing" to issue's Projects
- [ ] Shared on socials
- [x] Shared on newsletter. After checking this box, set Status to "Done" under "Articles" project and close issue.

**Comment by ursvill** [comment]
https://github.com/Green-Software-Foundation/sci-guide/issues/52#event-10408494062

**Comment by ursvill** [comment]
Draft article: https://docs.google.com/document/d/1iPLjX0fB6BX1uRPnGwpLr-SaSiwCUBbm/

**Comment by ursvill** [comment]
@Jenya-design - Can you look at the tables in this use case please and create a main image? Publish date early next week.

**Comment by Jenya-design** [comment]
@ursvill please check the update attached and [on Drive](https://drive.google.com/drive/folders/1pahCTPXcYDVnxoMnBnjJYK48dc6YizW8?usp=drive_link)
I didn't remake the charts in GSF style as it seems unnecessary in this context, but I made wider screenshots to fit our standard image width
Let me know what you think


![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/b9f97ebb-f34d-4c57-9762-ca2e518af609)

![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/4463e795-956c-471d-8e3d-fe846459f8e2)


![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/5e632df0-cd3e-4c82-84c0-22d244420f2e)

**Comment by ursvill** [comment]
@seanmcilroy29 - Sean, can you get me approval from the WG so I can publish?

**Comment by ursvill** [comment]
@Jenya-design - Thank you, this is great!

**Comment by ursvill** [comment]
Hey @seanmcilroy29 - just checking in to see if the WG approved this.

**Comment by NAMRATA-WOKE** [comment]
@seanmcilroy29 to follow-up tomorrow after SWG call and provide update.

**Comment by seanmcilroy29** [comment]
@ursvill - The SWG have approved to publish this use case
SCI-Guide GitHub link - https://github.com/Green-Software-Foundation/sci-guide/blob/dev/use-case-submissions/Automated_SCI_Measurements_with_Green_Metrics_Tool.md

**Comment by NAMRATA-WOKE** [comment]
@ursvill lets publish next week on Tuesday

**Comment by NAMRATA-WOKE** [comment]
@ursvill I noticed this didn't get published today. Can you please publish this tomorrow? Thanks.

**Comment by ursvill** [comment]
@NAMRATA-WOKE - You said, publish on Tue... Published now.

**Comment by NAMRATA-WOKE** [comment]
@ursvill sorry. I lost track of the days cause I had super long day yesterday and thought we missed our target. MY BAD!
