### ISSUE TITLE
[Interview] Mercedez Benz Member Interview

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/writers#162]
### Important Information
Author: @ursvill
Other contributors: @NAMRATA-WOKE
Article Link: (Link to the doc, must be in our official GSF drive)
Graphics Link: (Link to the design assets for this article, must be in our official GSF drive)
Published Link: (The link the article was published to for memory)

### Checklist

- [x]  Scheduled in calendar
- [x]  Google doc link created in GSF drive.
- [x]  In progress. After checking this box, set Status to "In Progress" under "Articles" project
- [x]  Draft created. After checking this box, set Status to "In Review" under "Articles" project. Assign issue to Reviewer/Author during the back-and-forth
- [x]  Draft reviewed. After checking this box, set Status to "In Publishing" under "Articles" project. Assign issue to Graphic Designer and add "Graphic Design" to issue's Projects
- [x]  Graphics created. After checking this box, assign to TBC for approval.
- [x]  Approved. After checking this box, assign to TBC for publishing.
- [x]  Published. After checking this box, set Status to "Ready" under "Articles" project. Assign to Marketing and add "D: Marketing" to issue's Projects
- [ ]  Shared on socials
- [x]  Shared on newsletter. After checking this box, set Status to "Done" under "Articles" project and close issue.

**Comment by NAMRATA-WOKE** [comment]
@NAMRATA-WOKE followed-up with Nic /copied Urs Lange. Waiting for response.

**Comment by ursvill** [comment]
![Image](https://github.com/Green-Software-Foundation/writers/assets/114167830/0fca8a32-32f4-4f1a-943f-c38197de096c)

**Comment by ursvill** [comment]
![Image](https://github.com/Green-Software-Foundation/writers/assets/114167830/4df3d946-24b0-42ba-9901-54771fccf0a6)

**Comment by ursvill** [comment]
https://docs.google.com/document/d/14rmgnu_-dXP3YD9o2Cu9g8nobL1V9dqX/

@NAMRATA-WOKE - For your review. Please see emails; this took about 3 months to get through comms, so we can't really change anything.

**Comment by ursvill** [comment]
@NAMRATA-WOKE - Please review / give go-ahead

**Comment by ursvill** [comment]
@Jenya-design - can you devise the imagery please

**Comment by Jenya-design** [comment]
Sure @ursvill please let me know when you're planning to publish

**Comment by Jenya-design** [comment]
Shall I use both photos for one quote?

**Comment by ursvill** [comment]
Up to Namrata

**Comment by ursvill** [comment]
> Shall I use both photos for one quote?

yes

**Comment by ursvill** [comment]
> @NAMRATA-WOKE - Please review / give go-ahead

@NAMRATA-WOKE - reminder

**Comment by Jenya-design** [comment]
@ursvill @NAMRATA-WOKE please review the images attached and [on Drive](https://drive.google.com/drive/folders/1yf4Kdl2M69L7TKqMcek_eQugkJxuc4Ra?usp=drive_link)

![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/7bef1fe1-c17c-4efe-9e64-764f5b45ed4b)


![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/036ba400-0f75-47d0-95ce-96ebdd45f58a)

**Comment by ursvill** [comment]
https://greensoftware.foundation/articles/minimizing-the-carbon-footprint-in-it-operations-meet-jorg-schwuchow-and-daniel-g
