### ISSUE TITLE
HCL Member Interview

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/writers#164]

**Comment by ursvill** [comment]
Sachidanand Sharma (Sachi)
HCLTech

draft early next week

**Comment by ursvill** [comment]
![Image](https://github.com/Green-Software-Foundation/writers/assets/114167830/22c89609-2382-45bc-95c5-5a7e1f8b1773)

**Comment by ursvill** [comment]
https://docs.google.com/document/d/12puIf2XJb4eQM2noRTmLWU-nLkqruxyS85_aq7HvS-M/

**Comment by ursvill** [comment]
@Jenya-design - Just working on this, can you create the images by Thu?

**Comment by Jenya-design** [comment]
Yes @ursvill please give me a quote when it's ready
Thank you

**Comment by ursvill** [comment]
@NAMRATA-WOKE - If you can review tdy or tmr, I can still get this out this week.

**Comment by NAMRATA-WOKE** [comment]
@ursvill yes reviewing today!

**Comment by ursvill** [comment]
@Jenya-design - Quote:
“Many developers and businesses are unaware of the environmental impact of software, or the benefits of green software development.”

**Comment by Jenya-design** [comment]
@ursvill please check the update attached and [on Drive](https://drive.google.com/drive/folders/15MQeFkF8R-5orMpeJJ0LxPoLH4azvIuB?usp=drive_link)

![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/40b0c1a4-9d7b-4784-b87e-bad2d3b83244)

![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/a9bb0779-c6e8-40b7-a6c2-76b076c8b84b)

**Comment by ursvill** [comment]
@NAMRATA-WOKE - published
