### ISSUE TITLE
EV: Decarb Debrief Episode

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/writers#165]
- Guest:  @adamj89 
- Potential Date: Next couple of weeks
- Topic:  **Decarb debrief** 

> Contact History:
- Sent message to @adamj89 on Slack 20/11/2023
- Follow up Slack message sent on 24/11/2023
- Email sent on 27/11/2023

**Comment by zanete** [comment]
@sonicfutures as per your ask here https://github.com/Green-Software-Foundation/gsf-admin/issues/356#issuecomment-1809574153, @adamj89 has said he's happy to help with the debrief. 

He's got some questions to you about how that would happen, so I created this placeholder issue on the Podcast project board for you to discuss. If you've got one already, please feel free to direct him there and archive this one.

**Comment by sonicfutures** [comment]
Hey @adamj89 sent you a message about doing this on **Slack**, please let me know if there are any dates in the next few weeks that work for you :)

**Comment by sonicfutures** [comment]
Draft script has been produced for this episode here:
https://docs.google.com/document/d/1CiUrJeA2d4n_vAm16WAgS_4pZI_qJ5rQ8ABycCyTKrM/edit?usp=sharing
