### ISSUE TITLE
[Article] Summary of Decarb 2023

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/writers#166]
## Article Details
_Please enter the details here_

**Proposer**: Namrata Narayan | Dir. Comms & Member Relations | @NAMRATA-WOKE 
**Abstract**: Recapping Decarb 2023, covering the agenda and community-led sessions, sharing key perspectives, questions and moments. 
**Why**: For people who could not attend and might not feel inclined to watch the on-demand video
**Audience**: Everyone
**Timeline**: Week of Nov 20

## Important Information
_To be filled out later_

**Author**: @ursvill 
**Other contributors**: @NAMRATA-WOKE + speakers 
**Article Link**: (Link to the doc, must be in our official GSF drive)
**Graphics Link**: (Link to the design assets for this article, must be in our official GSF drive)
**Published Link**: (The link the article was published to for memory)

## Checklist
- [x] Idea discussed and selected for writing. _After checking this box, set Status to "Todo" under "Articles" project_
- [x] Author identified. _After checking this box Assign issue to the Author_
- [ ] Scheduled in calendar
- [x] Google doc link created in GSF drive. 
- [x] In progress. _After checking this box, set Status to "In Progress" under "Articles" project_
- [x] Draft created. _After checking this box, set Status to "In Review" under "Articles" project. Assign issue to Reviewer/Author during the back-and-forth_
- [ ] Draft reviewed. _After checking this box, set Status to "In Publishing" under "Articles" project. Assign issue to Graphic Designer and add "Graphic Design" to issue's Projects_
- [ ] Graphics created. _After checking this box, assign to TBC for approval._
- [ ] Approved. _After checking this box, assign to TBC for publishing._
- [ ] Published. After checking this box, set Status to "Ready" under "Articles" project. Assign to Marketing and add "D: Marketing" to issue's Projects
- [ ] Shared on socials
- [ ] Shared on newsletter. After checking this box, set Status to "Done" under "Articles" project and close issue.

**Comment by NAMRATA-WOKE** [comment]
@ursvill can you work on this and have a first draft ready for EOD Monday?

[Watch the on-demand video](https://grnsft.org/decarb)

Supporting Docs:

[Responsible AI Panel Planning Doc](https://docs.google.com/document/d/1AlTtBZKqHVaqZ58QDcepdn6DwgD9hx8hpYNb8tpd-7Q/edit)

[Run of Show](https://docs.google.com/document/d/1DtR8iK08JqUUCWDWpPY63AzUUa_NJDjmqyICf3vQK0U/edit)

- This document shares our talking points and key questions from the audience

**Comment by ursvill** [comment]
@NAMRATA-WOKE - Is there a transcript?

**Comment by NAMRATA-WOKE** [comment]
@ursvill dont think so!

**Comment by ursvill** [comment]
If this was recorded straight to Youtube, can you give me the login?

**Comment by ursvill** [comment]
@NAMRATA-WOKE - here is the draft. I think we need to add a few of the slides for more context. Can the presenters do a quick review of their sections?

https://docs.google.com/document/d/1ypgT4HwGUol-KKWNS3mT8hfjNvvUZWw4/

**Comment by ursvill** [comment]
@NAMRATA-WOKE - publishing now; LMK if any changes are needed
