### ISSUE TITLE
Update website banner to book of news

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/writers#171]
Update website banner on homepage to go:

View our Book of News for 2023

Read now

Button link: https://greensoftware.foundation/articles/green-software-foundation-book-of-news-2023

**Comment by NAMRATA-WOKE** [comment]
@osamajandali @zanete can I get a status update on this?

**Comment by zanete** [comment]
strange that it was added in a past sprint, hence didn't come to my attention. It's best to tag myself in any new issues. @osamajandali can this be included in this weeks work?

**Comment by osamajandali** [comment]
Done
