### ISSUE TITLE
EV: BETA Impact Framework Episode w Asim (H), Navveen Balani and Srini Rakhunathan

### ISSUE THREAD

**Issue by sonicfutures** [Green-Software-Foundation/writers#173]
- Guests: **Navveen Balani** and **Srini Rakhunathan**
- Potential Date: **Late January/Early Feb**
- Topic:  **Green Software Foundations Impact Framework Episode**

> Contact History:

- Email thread started on Mon Nov 27
- Can be used to promote Hackathon suggestion by @NAMRATA-WOKE 
- Another follow up email sent on **Dec 15**

**Comment by sonicfutures** [comment]
This episode has been published!

**Comment by sonicfutures** [comment]
Booked with @jawache Srini and Navveen for the 16th at 2pm GMT

Episode Sheet:
https://docs.google.com/document/d/1VS-M-fC7mh9c38tucqD-RAEB1M2UWzpz3_5A325p-E8/edit?usp=sharing 

Riverside Studio Link:
https://riverside.fm/studio/ev-episode-58-beta-impact-framework?t=091a482c3c806dd8375b

**Comment by NAMRATA-WOKE** [comment]
FYI @jawache.
