### ISSUE TITLE
[Article] Introducing Carbon Hack 24

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/writers#175]
## Article Details
_Please enter the details here_

**Proposer**: Namrata Narayan | Dir. Comms & Member Relations | @NAMRATA-WOKE 
**Abstract**: What Carbon Hack 24 is all about 
**Why**: generate awareness about impact framework, the importance of measurement and interest among developers in participating. 
**Audience**: Software developers
**Timeline**: December 11

## Important Information
_To be filled out later_

**Author**: @ursvill 
**Other contributors**: @NAMRATA-WOKE @adamj89 
**Article Link**: (Link to the doc, must be in our official GSF drive)
**Graphics Link**: (Link to the design assets for this article, must be in our official GSF drive)
**Published Link**: (The link the article was published to for memory)

## Checklist
- [x] Idea discussed and selected for writing. _After checking this box, set Status to "Todo" under "Articles" project_
- [x] Author identified. _After checking this box Assign issue to the Author_
- [x] Scheduled in calendar
- [x] Google doc link created in GSF drive. 
- [x] In progress. _After checking this box, set Status to "In Progress" under "Articles" project_
- [x] [Draft created](https://docs.google.com/document/d/1qyvuLJjmZ5B6y0f0ABI-kbQ_9XGDtXrc/). _After checking this box, set Status to "In Review" under "Articles" project. Assign issue to Reviewer/Author during the back-and-forth_
- [x] Draft reviewed. _After checking this box, set Status to "In Publishing" under "Articles" project. Assign issue to Graphic Designer and add "Graphic Design" to issue's Projects_
- [x] Graphics created. _After checking this box, assign to TBC for approval._
- [ ] Approved. _After checking this box, assign to TBC for publishing._
- [x] Published. After checking this box, set Status to "Ready" under "Articles" project. Assign to Marketing and add "D: Marketing" to issue's Projects
- [ ] Shared on socials
- [ ] Shared on newsletter. After checking this box, set Status to "Done" under "Articles" project and close issue.

**Comment by NAMRATA-WOKE** [comment]
@ursvill 

Resources to support writing the article: 

https://docs.google.com/presentation/d/13IqItz50G3jrsjOlyt4vZtSejUW29TEe/edit#slide=id.g29f4e8e104a_0_256
https://docs.google.com/document/d/18Ye2rNAmXmi3hoU7AvsNMR77chvEIV5gmbBnuEMMCvA/edit#heading=h.8021jr7i9u1n

**Comment by zanete** [comment]
@ursvill hey! How is this going, do you have everything you need? 
There are a couple of new resources available to you through https://github.com/Green-Software-Foundation/carbonhack-event/issues/152 and https://github.com/Green-Software-Foundation/carbonhack-event/issues/160

**Comment by ursvill** [comment]
Draft is here: https://docs.google.com/document/d/1qyvuLJjmZ5B6y0f0ABI-kbQ_9XGDtXrc/

**Comment by NAMRATA-WOKE** [comment]
@jawache let me know if there's anything you want changed. 

FYI @zanete

**Comment by jawache** [comment]
@NAMRATA-WOKE and @ursvill thanks added comments

**Comment by NAMRATA-WOKE** [comment]
@ursvill DO NOT PUBLISH this article until Monday morning! Change in schedule. Thanks.

**Comment by ursvill** [comment]
@NAMRATA-WOKE - published

**Comment by jawache** [comment]
Test

Asim
http://www.bubblegumhq.com
***@***.***
UK: +44 (0) 753 222 0032



*"We make web & mobile apps that just pop"*




Sent via Superhuman ***@***.***>

**Comment by jawache** [comment]
test

Asim
http://www.bubblegumhq.com
***@***.***
UK: +44 (0) 753 222 0032



*"We make web & mobile apps that just pop"*




Sent via Superhuman ***@***.***>
