### ISSUE TITLE
[Article] Summaries of Carbon Hack Weekly Live Sessions

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/writers#188]
## Article Details
_Please enter the details here_

**Proposer**: Namrata Narayan | Dir. Comms & Member Relations | @NAMRATA-WOKE 
**Abstract**: Unlike other event summaries, this will be short and sweet (reader's digest version) and will link to the recording on YT
**Why**: Keep participants looped in and also provided added information for practitioners interested in IF - use this opportunity to also thank sponsors
**Audience**: Carbon Hack participants
**Timeline**: Dec - 18 - March 15 

## Important Information
_To be filled out later_

**Author**: @ursvill 
**Other contributors**: @NAMRATA-WOKE @jawache 
**Graphics Link**: @Jenya-design can you create standard banner for all these updates for articles 

## Summaries Checklist 
**_Note: Lives occur on Monday. Summaries to be published following Thursday on the same week._** 

- [ ] December 18 live (summary to be published following Thursday) 
- [ ] Monday, 8 January live 
- [ ] Monday, 15 January live 
- [ ] Monday, 22 January live 
- [ ] Monday, 29 January live 
- [ ] Monday, 5 February live 
- [ ] Monday, 12 February live 
- [ ] Monday, 19 February live 
- [ ] Monday, 26 February live 
- [ ] Monday, 4 March live 
- [ ] Monday, 11 March 2024
- [ ] Friday, 15 March 2024

**Comment by NAMRATA-WOKE** [comment]
@ursvill these live sessions take place on Mondays at 2:00 pm GMT. If you can attend them, that might be best. If not, please let me know.

**Comment by NAMRATA-WOKE** [comment]
@zanete is there a way to add the labels for Carbon Hack to this issue? It's in the writer's repo right now. Not able to change it to Carbon Hack repo.

**Comment by Jenya-design** [comment]
@NAMRATA-WOKE this is the same banner / article cover as in issue [#209](https://github.com/Green-Software-Foundation/carbonhack-event/issues/209)?

**Comment by NAMRATA-WOKE** [comment]
@Jenya-design yes please update the other issue. I thought I deleted this one!

**Comment by NAMRATA-WOKE** [comment]
Scrapped.
