### ISSUE TITLE
[Interview] New Member HARC

### ISSUE THREAD

**Issue by ursvill** [Green-Software-Foundation/writers#193]
## Article Details
_Please enter the details here_

**Proposer**: (who is proposing this article idea, Name | Affiliation | GitHub Username)
**Abstract**: (50 word summary of the article)
**Why**: (Why is this article an important topic to discuss and how is it related to the work/mission/theory of change of the GSF)
**Audience**: (Which audience is most going to connect to the content in this article)
**Timeline**: (Should this article come out before or after an important date)

## Important Information
_To be filled out later_

**Author**: (Who is assigned to write this article)
**Other contributors**: (Experts, Reviewers)
**Article Link**: (Link to the doc, must be in our official GSF drive)
**Graphics Link**: (Link to the design assets for this article, must be in our official GSF drive)
**Published Link**: (The link the article was published to for memory)

## Checklist
- [x] Idea discussed and selected for writing. _After checking this box, set Status to "Todo" under "Articles" project_
- [x] Author identified. _After checking this box Assign issue to the Author_
- [x] Scheduled in calendar
- [x] [Google doc link](https://docs.google.com/document/d/1DLGNVrW_SqxhaOAOkUQljhhwSlT6MDVL/) created in GSF drive. 
- [x] In progress. _After checking this box, set Status to "In Progress" under "Articles" project_
- [x] Draft created. _After checking this box, set Status to "In Review" under "Articles" project. Assign issue to Reviewer/Author during the back-and-forth_
- [x] Draft reviewed. _After checking this box, set Status to "In Publishing" under "Articles" project. Assign issue to Graphic Designer and add "Graphic Design" to issue's Projects_
- [x] Graphics created. _After checking this box, assign to TBC for approval._
- [x] Approved. _After checking this box, assign to TBC for publishing._
- [x] Published. After checking this box, set Status to "Ready" under "Articles" project. Assign to Marketing and add "D: Marketing" to issue's Projects
- [ ] Shared on socials
- [ ] Shared on newsletter. After checking this box, set Status to "Done" under "Articles" project and close issue.

**Comment by ursvill** [comment]
sent questions

**Comment by ursvill** [comment]
Thanks Urs. We can manage that. I will have something to you by close of business Friday, February 16th.
 
Have a good weekend.
 
--Stacy

**Comment by ursvill** [comment]
![Carlos_Gamarra](https://github.com/Green-Software-Foundation/writers/assets/114167830/30591164-5542-4c3e-a464-c603eefc6bd7)

**Comment by ursvill** [comment]
here is my draft: https://docs.google.com/document/d/1DLGNVrW_SqxhaOAOkUQljhhwSlT6MDVL/
@NAMRATA-WOKE

**Comment by NAMRATA-WOKE** [comment]
@Jenya-design can you quickly create graphics for this so I can publish the article today?

**Comment by ursvill** [comment]
@NAMRATA-WOKE - client has not had a chance to do a review with the changes. Are your changes complete?

**Comment by NAMRATA-WOKE** [comment]
@ursvill yes, please get approval!

**Comment by Jenya-design** [comment]
@ursvill @NAMRATA-WOKE please check the images attached and [on Drive](https://drive.google.com/drive/folders/1bqxShNtg8cvaBgm4X7CjjNcsGPSuGWOZ?usp=drive_link)

![GeneralMember-Dr-Carlos-Gamarra-HARC-GreenSoftwareFoundation-1](https://github.com/Green-Software-Foundation/writers/assets/69306070/224770ab-8998-4076-a863-e002b9fadd59)

![GeneralMember-Dr-Carlos-Gamarra-HARC-GreenSoftwareFoundation-2](https://github.com/Green-Software-Foundation/writers/assets/69306070/ef4bb253-7feb-40b4-a8c8-a4c1440e68b1)

**Comment by ursvill** [comment]
published

**Comment by NAMRATA-WOKE** [comment]
Thanks @ursvill
