### ISSUE TITLE
Spruce up design for one-pager on projects

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/writers#206]
Pindy from UBS put this together - can you adapt it with our branding? 

https://docs.google.com/presentation/d/1X0IlEhnR77k5XgVhZRF9GeMqBlJHc2Fq/edit?usp=drive_link&ouid=102812099925850911550&rtpof=true&sd=true

**Comment by NAMRATA-WOKE** [comment]
Please note Usage of Software Emissions project now has a different name: Transforming Organizational Software Sustainability

**Comment by seanmcilroy29** [comment]
@NAMRATA-WOKE - FYI - I'm waiting for some final comments before the scope is approved this week. Once approved, I'll submit a couple of issues to draft a project article and logo.

**Comment by Jenya-design** [comment]
@NAMRATA-WOKE slide is updated, please review
