### ISSUE TITLE
[Interview] New Member Ahmad Antar, Digital Emissions

### ISSUE THREAD

**Issue by ursvill** [Green-Software-Foundation/writers#207]
## Article Details
_Please enter the details here_

**Proposer**: (who is proposing this article idea, Name | Affiliation | GitHub Username)
**Abstract**: (50 word summary of the article)
**Why**: (Why is this article an important topic to discuss and how is it related to the work/mission/theory of change of the GSF)
**Audience**: (Which audience is most going to connect to the content in this article)
**Timeline**: (Should this article come out before or after an important date)

## Important Information
_To be filled out later_

**Author**: (Who is assigned to write this article)
**Other contributors**: (Experts, Reviewers)
**Article Link**: (Link to the doc, must be in our official GSF drive)
**Graphics Link**: (Link to the design assets for this article, must be in our official GSF drive)
**Published Link**: (The link the article was published to for memory)

## Checklist
- [x] Idea discussed and selected for writing. _After checking this box, set Status to "Todo" under "Articles" project_
- [x] Author identified. _After checking this box Assign issue to the Author_
- [x] Scheduled in calendar
- [x] Google doc link created in GSF drive. 
- [x] In progress. _After checking this box, set Status to "In Progress" under "Articles" project_
- [x] Draft created. _After checking this box, set Status to "In Review" under "Articles" project. Assign issue to Reviewer/Author during the back-and-forth_
- [x] Draft reviewed. _After checking this box, set Status to "In Publishing" under "Articles" project. Assign issue to Graphic Designer and add "Graphic Design" to issue's Projects_
- [x] Graphics created. _After checking this box, assign to TBC for approval._
- [x] Approved. _After checking this box, assign to TBC for publishing._
- [x] Published. After checking this box, set Status to "Ready" under "Articles" project. Assign to Marketing and add "D: Marketing" to issue's Projects
- [ ] Shared on socials
- [ ] Shared on newsletter. After checking this box, set Status to "Done" under "Articles" project and close issue.

**Comment by ursvill** [comment]
@NAMRATA-WOKE - ready for your review
https://docs.google.com/document/d/1K4ywIjJ8kmeWc2N5wWIcf5ePmYZWjiiPQDBWhZu-HGs/

**Comment by NAMRATA-WOKE** [comment]
Done my review. @ursvill

**Comment by ursvill** [comment]
@Jenya-design - can you create the graphics
Quote
“I think we’re close to starting to see GreenOps integrated into the software development lifecycle in the same way that SecOPS is today.“

**Comment by ursvill** [comment]
![AAntar](https://github.com/Green-Software-Foundation/writers/assets/114167830/7070300b-0ba6-4ddf-9507-2671c031dac5)

**Comment by Jenya-design** [comment]
@ursvill please check the update attached and [on Drive](https://drive.google.com/drive/folders/1g47W69k5k4u_5GGaD0lpN-X6dHhjIgVw?usp=drive_link)

![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/b3e61611-b304-4f0f-b04b-b6f0fb2e2947)

![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/caa2ceba-b80c-459d-b713-4e33a3b2cd50)

**Comment by NAMRATA-WOKE** [comment]
@Jenya-design looks good, thank you!

**Comment by ursvill** [comment]
published 
https://greensoftware.foundation/articles/meet-ahmad-antar-digital-emissions
