### ISSUE TITLE
[Article] Carbon Aware SDK Graduation

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/writers#213]
## Article Details
**Proposer**: Sophie Trinder | Senior Technical PM | @Sophietn 
**Abstract**: The CASDK graduates on the 29th February. It is stable, mature and ready for wider industry adoption. [THIS](https://github.com/Green-Software-Foundation/oc/issues/79) shows the project team is fulfilling all the criteria to graduate. For reference, OC Project Lifecycle [Graduation requirements](https://oc.greensoftware.foundation/project-lifecycle.html#graduated). Drive traffic to [Set Up Guide](https://carbon-aware-sdk.greensoftware.foundation/docs/quickstart).
**Why**: Celebrate Graduation. Increase adoption of CASDK 
**Audience**: Software developers 
**Timeline**: March 2024

## Important Information

**Author**: @Sophietn 
**Other contributors**: @NAMRATA-WOKE @ursvill 
**Article Link**: https://docs.google.com/document/d/1o1XK4FGPIHHxkNKsedLgFDRiwkX4tDj2zdCS5X0OXmI/edit
**Graphics Link**: (Link to the design assets for this article, must be in our official GSF drive)
**Published Link**: (The link the article was published to for memory)

## Checklist
- [x] Idea discussed and selected for writing. _After checking this box, set Status to "Todo" under "Articles" project_
- [x] Author identified. _After checking this box Assign issue to the Author_
- [x] Scheduled in calendar
- [x] Google doc link created in GSF drive. 
- [x] In progress. _After checking this box, set Status to "In Progress" under "Articles" project_
- [x] Draft created. _After checking this box, set Status to "In Review" under "Articles" project. Assign issue to Reviewer/Author during the back-and-forth_
- [x] Draft reviewed. _After checking this box, set Status to "In Publishing" under "Articles" project. Assign issue to Graphic Designer and add "Graphic Design" to issue's Projects_
- [x] Graphics created. _After checking this box, assign to TBC for approval._
- [x] Approved. _After checking this box, assign to TBC for publishing._
- [x] Published. After checking this box, set Status to "Ready" under "Articles" project. Assign to Marketing and add "D: Marketing" to issue's Projects
- [x] Shared on socials
- [x] Shared on newsletter. After checking this box, set Status to "Done" under "Articles" project and close issue.

**Comment by Sophietn** [comment]
@NAMRATA-WOKE gave some initial feedback. Back In Progress for @Sophietn to continue drafting next week

**Comment by Jenya-design** [comment]
@NAMRATA-WOKE please check the illustration attached and [on Drive](https://drive.google.com/drive/folders/1-1r5iw9YR_Ow9Qz7LBLX68EenPMGStyI?usp=sharing)

![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/d2c47882-ea9c-4512-98fc-8e594e6b7496)

**Comment by Sophietn** [comment]
@NAMRATA-WOKE @seanmcilroy29 flagged we should have got the OSWG to review the article ahead of publishing it
