### ISSUE TITLE
[ARTICLE] CAST Software Case Study

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/writers#221]
## Article Details
_Please enter the details here_

**Proposer**: Greg Rivera | VP of Product | @pgregrivera
**Abstract**: [(50 word summary of the article)](https://github.com/orgs/Green-Software-Foundation/projects/21/views/1?filterQuery=cast&pane=issue&itemId=57619206)
**Why**: Raise awareness about application of SCI in measuring software emissions
**Audience**: Product leads and software engineers
**Timeline**: March 2024

## Important Information
_To be filled out later_

**Author**: @ursvill 
**Other contributors**: @NAMRATA-WOKE 
**Article Link**: [(Link to the doc, must be in our official GSF drive)](https://docs.google.com/document/d/1xmcUjH9DeD2DVJ1fo8cGdD8G9puQr_2C/edit)
**Graphics Link**: (Link to the design assets for this article, must be in our official GSF drive)
**Published Link**: (The link the article was published to for memory)

## Checklist
- [x] Idea discussed and selected for writing. _After checking this box, set Status to "Todo" under "Articles" project_
- [x] Author identified. _After checking this box Assign issue to the Author_
- [x] Scheduled in calendar
- [x] Google doc link created in GSF drive. 
- [x] In progress. _After checking this box, set Status to "In Progress" under "Articles" project_
- [x] Draft created. _After checking this box, set Status to "In Review" under "Articles" project. Assign issue to Reviewer/Author during the back-and-forth_
- [x] Draft reviewed. _After checking this box, set Status to "In Publishing" under "Articles" project. Assign issue to Graphic Designer and add "Graphic Design" to issue's Projects_
- [x] Graphics created. _After checking this box, assign to TBC for approval._
- [x] Approved. _After checking this box, assign to TBC for publishing._
- [x] Published. After checking this box, set Status to "Ready" under "Articles" project. Assign to Marketing and add "D: Marketing" to issue's Projects
- [ ] Shared on socials
- [ ] Shared on newsletter. After checking this box, set Status to "Done" under "Articles" project and close issue.

**Comment by NAMRATA-WOKE** [comment]
@Jenya-design is it possible for you to complete the graphic today? If not, I'll try and see if I can use one we've banked.

**Comment by Jenya-design** [comment]
@NAMRATA-WOKE I'll put something together today

**Comment by Jenya-design** [comment]
@NAMRATA-WOKE please check the update attached and [on Drive](https://drive.google.com/drive/folders/1S-6cEVE35uErJ1tzyv-9U2ac_cptSdS8?usp=drive_link)

![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/0f38b84f-9436-47be-9e7a-04eac2247ac6)

**Comment by ursvill** [comment]
@Jenya-design - can you do something with the SCI formula? Maybe you already have that in a nicer form (I just put it in frames)

**Comment by Jenya-design** [comment]
@ursvill we have this illustration for the formula, do you want me to update it to match your text?
Or you prefer not to use illustration, just update text formatting to make the formula stand out?

![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/a10bbab4-1f59-400c-9501-0a450763926b)

**Comment by ursvill** [comment]
@Jenya-design - This is fantastic, so if you can update it that would be great!

**Comment by Jenya-design** [comment]
@ursvill please review two options - with and without examples

![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/1ab97c24-84df-4389-8499-059845ad9bbb)

![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/409df3ac-1bce-40ba-a6fd-8b8862bfb63d)

**Comment by ursvill** [comment]
https://greensoftware.foundation/articles/decarbonizing-software-how-cast-applied-the-sci-metric
