### ISSUE TITLE
[Article] Sustainability: From Environmental Aim to Business Imperative

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/writers#224]
## Article Details
_Please enter the details here_

**Proposer**: Namrata Narayan | Dir. Comms & Member Relations | @NAMRATA-WOKE 
Abstract: Article capturing key points, insights, while offering additional context on recent podcast episode.
Why: Repurpose content and use GSF website as a channel to scale reach and impact of the podcast
Audience: Software Developers
Timeline: April 2024

## Important Information
_To be filled out later_

**Author**: Freelancer, Malgorzata F.
**Other contributors**: @NAMRATA-WOKE 
**Article Link**: [Link to the doc, must be in our official GSF drive)](https://docs.google.com/document/d/1Wq9YW-Wy-cXDtQeXr48YclzcN7gfMRJVr4IJnPEbVQE/edit#heading=h.21ph0icw1cqh)
**Graphics Link**: (Link to the design assets for this article, must be in our official GSF drive)
**Published Link**: (The link the article was published to for memory)

## Checklist
- [x] Idea discussed and selected for writing. _After checking this box, set Status to "Todo" under "Articles" project_
- [x] Author identified. _After checking this box Assign issue to the Author_
- [x] Scheduled in calendar
- [x] Google doc link created in GSF drive. 
- [x] In progress. _After checking this box, set Status to "In Progress" under "Articles" project_
- [x] Draft created. _After checking this box, set Status to "In Review" under "Articles" project. Assign issue to Reviewer/Author during the back-and-forth_
- [x] Draft reviewed. _After checking this box, set Status to "In Publishing" under "Articles" project. Assign issue to Graphic Designer and add "Graphic Design" to issue's Projects_
- [x] Graphics created. _After checking this box, assign to TBC for approval._
- [x] Approved. _After checking this box, assign to TBC for publishing._
- [x] Published. After checking this box, set Status to "Ready" under "Articles" project. Assign to Marketing and add "D: Marketing" to issue's Projects
- [x] Shared on socials
- [x] Shared on newsletter. After checking this box, set Status to "Done" under "Articles" project and close issue.

**Comment by jawache** [comment]
FYI @NAMRATA-WOKE we only need this issue on this board: [April-2024 Content Calendar #216](https://github.com/Green-Software-Foundation/writers/issues/216) more for others to see what's working on in general, individual article issues remain in the writers board.

**Comment by NAMRATA-WOKE** [comment]
@Jenya-design sorry for the tight turnaround, can you create an image for this? This is an article that repurposes content from the Environment Variables podcast.

**Comment by Jenya-design** [comment]
@NAMRATA-WOKE please check the image attached and [on Drive](https://drive.google.com/drive/folders/1ytcCjaoOJVsYz2jtp9419D9GSKPBw2nA?usp=sharing)

![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/37a01fa7-3e0f-49e9-bd50-5cfd4803d6b3)
