### ISSUE TITLE
[Article] GSF's Recommended Reading List 

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/writers#226]
## Article Details
_Please enter the details here_

**Proposer**: Anne Currie | Tech Ethicist Consultant, Re:cinq
**Abstract**: List of green software books recommended by GSF champions
**Why**: Improve knowledge of green software theory, principles, patterns and best practices
**Audience**: Software developers
**Timeline**: June 2024

## Important Information
_To be filled out later_

**Author**: Freelancer
**Other contributors**: @NAMRATA-WOKE 
**Article Link**: (Link to the doc, must be in our official GSF drive)
**Graphics Link**: (Link to the design assets for this article, must be in our official GSF drive)
**Published Link**: (The link the article was published to for memory)

## Checklist
- [x] Idea discussed and selected for writing. _After checking this box, set Status to "Todo" under "Articles" project_
- [x] Author identified. _After checking this box Assign issue to the Author_
- [x] Scheduled in calendar
- [x] [Google doc link created in GSF drive](https://docs.google.com/document/d/1R6gM2owiWHFTjtU7PbRSVps_mUkGj_WMSJLT_70Ci9U/edit). 
- [x] In progress. _After checking this box, set Status to "In Progress" under "Articles" project_
- [x] Draft created. _After checking this box, set Status to "In Review" under "Articles" project. Assign issue to Reviewer/Author during the back-and-forth_
- [ ] Draft reviewed. _After checking this box, set Status to "In Publishing" under "Articles" project. Assign issue to Graphic Designer and add "Graphic Design" to issue's Projects_
- [ ] Graphics created. _After checking this box, assign to TBC for approval._
- [ ] Approved. _After checking this box, assign to TBC for publishing._
- [ ] Published. After checking this box, set Status to "Ready" under "Articles" project. Assign to Marketing and add "D: Marketing" to issue's Projects
- [ ] Shared on socials
- [ ] Shared on newsletter. After checking this box, set Status to "Done" under "Articles" project and close issue.

**Comment by NAMRATA-WOKE** [comment]
Shared by Asim and Anne Currie in an email to Namrata

https://www.amazon.co.uk/Sustainable-Playbook-Technology-Leaders-opportunities/dp/1803230347
[https://www.amazon.co.uk/GREEN-SOFTWARE-ESSENTIALS-GUIDE-PRACTITIONERS/dp/B0CNPZ3465/[…]books&sprefix=green+software+essentials,stripbooks,72&sr=1-1](https://www.amazon.co.uk/GREEN-SOFTWARE-ESSENTIALS-GUIDE-PRACTITIONERS/dp/B0CNPZ3465/ref=sr_1_1?crid=1E12EEWBSJQ77&dib=eyJ2IjoiMSJ9.4j7s39I1cmOkwSKfmG2qo4uJNXrbXW1qmI1EyPgmhttTINHtfmzHaQQ1vqDnqY_EahfC69tYUrfm8nwvYWUoIz1Dx75pJnKVydprmGidUf2jShagHvz9P6HtDvvLPKbvQSZPdxvtOUIatejjU0jDUd-It1MCtngvJRx32OoFyIMZVovVMQ9brTjDxH_7WdZLam6rGoVVlrdqzuY742xOTxSoPWuA6PVY4hdK-oF47KY.4ZQOuZzdfLHKGRMZYdn8qVqfSZL0xOMpWkZ8gzx0JDw&dib_tag=se&keywords=Green+Software+Essentials&qid=1712659563&s=books&sprefix=green+software+essentials,stripbooks,72&sr=1-1)
[https://www.amazon.co.uk/Sustainable-Web-Design-Tom-Greenwood/dp/1952616034/ref=sr_1_[…]&s=books&sprefix=sustainable+web+design,stripbooks,71&sr=1-1](https://www.amazon.co.uk/Sustainable-Web-Design-Tom-Greenwood/dp/1952616034/ref=sr_1_1?crid=OMTWFGBRDD48&dib=eyJ2IjoiMSJ9.bcghJ3r242-6ug2R8e8vNvUHTXp0ndNIP0lnc8iiXRV4xLcIvWp-O6sG9HQx5zqDqWXs6V49x425xQeyb-Q6PleBLlN4Qdj5jdk2wiANDC2-cbbKH55Tdyqo6OSpQNlN5jDs8oCxtB93nlwhc1VJ-mV0Puz1-PsdYPqu2FJaefJZ7TYx6JXGAUuU8mxZQm86hsOV4Lql7p-zU1WkLgtoaO91CemD7iJYVDnt381nUj4.cz9D683JsK9nJlDuDKS46Z-haKIioIH1j1RgGhOsNdU&dib_tag=se&keywords=Sustainable+Web+Design&qid=1712659581&s=books&sprefix=sustainable+web+design,stripbooks,71&sr=1-1)
[https://www.amazon.co.uk/Designing-Sustainability-Tim-Frick/dp/1491935774/ref=pd_sbs_[…]298a17d-a86c-4e64-85f3-8d1bd8166cf4&pd_rd_i=1491935774&psc=1](https://www.amazon.co.uk/Designing-Sustainability-Tim-Frick/dp/1491935774/ref=pd_sbs_d_sccl_2_1/257-2151180-5698350?pd_rd_w=FBqkg&content-id=amzn1.sym.ad51136c-8d04-4e54-9ec5-18cad2a65d61&pf_rd_p=ad51136c-8d04-4e54-9ec5-18cad2a65d61&pf_rd_r=GN5G0VYPP6989HZWPW34&pd_rd_wg=OG1JO&pd_rd_r=8298a17d-a86c-4e64-85f3-8d1bd8166cf4&pd_rd_i=1491935774&psc=1)
https://www.amazon.co.uk/dp/B0BPPF82H9?linkId=c31382a6e2c96bd7ef6c8113d5f9940d&tag=buildbetter0b-20&creative=9325&camp=1789
https://link.springer.com/book/10.1007/978-3-030-69970-3

**Comment by Jenya-design** [comment]
@NAMRATA-WOKE please check the illustration attached and [on Drive](https://drive.google.com/drive/folders/1A8aa9q8QAv597PKSX91hDFziU0Zho8mJ?usp=drive_link)

![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/2c31f443-d1ff-4cd1-8c2d-965836592908)
