### ISSUE TITLE
[Article] HSBC Q&A Article

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/writers#244]
## Article Details
_Please enter the details here_

Introducing HSBC in Q&A style interview article.
https://docs.google.com/document/d/12971hsyRQLJXIqk7VbwnUCR1Mo5BvcH_/edit

## Important Information
_To be filled out later_

**Author**: (Who is assigned to write this article)
**Other contributors**: (Experts, Reviewers)
**Article Link**: (Link to the doc, must be in our official GSF drive)
**Graphics Link**: (Link to the design assets for this article, must be in our official GSF drive)
**Published Link**: (The link the article was published to for memory)

## Checklist
- [x] Idea discussed and selected for writing. _After checking this box, set Status to "Todo" under "Articles" project_
- [x] Author identified. _After checking this box Assign issue to the Author_
- [x] Scheduled in calendar
- [x] Google doc link created in GSF drive. 
- [x] In progress. _After checking this box, set Status to "In Progress" under "Articles" project_
- [x] Draft created. _After checking this box, set Status to "In Review" under "Articles" project. Assign issue to Reviewer/Author during the back-and-forth_
- [x] Draft reviewed. _After checking this box, set Status to "In Publishing" under "Articles" project. Assign issue to Graphic Designer and add "Graphic Design" to issue's Projects_
- [ ] Graphics created. _After checking this box, assign to TBC for approval._
- [ ] Approved. _After checking this box, assign to TBC for publishing._
- [ ] Published. After checking this box, set Status to "Ready" under "Articles" project. Assign to Marketing and add "D: Marketing" to issue's Projects
- [ ] Shared on socials
- [ ] Shared on newsletter. After checking this box, set Status to "Done" under "Articles" project and close issue.

**Comment by NAMRATA-WOKE** [comment]
@Jenya-design can you please create the assets for this member interview?

The quote for the image card: 

At HSBC, we want to give our technology teams tools and resources to learn about green software best practices and patterns and contribute to the GSF's working groups. Our aim is to pioneer, along with the GSF, in co-creating innovations and solutions to benefit the technology industry’s approach to green software.

**Comment by Jenya-design** [comment]
@NAMRATA-WOKE could you also give me the photo and the name of the speaker. I can't see those as I can't access the doc
Please let me know if you want a bit different design for this article. As I understand Q&A is a bit different format of members' intro
cc @ursvill

**Comment by Jenya-design** [comment]
@NAMRATA-WOKE please check the images for the article attached and [on Drive](https://drive.google.com/drive/folders/1qXGc76QQs0YrxU3VFGp05KmeP-jHbI2p?usp=sharing)

![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/11247aa2-596c-486d-bdd3-9f251d99bed3)

![Image](https://github.com/Green-Software-Foundation/writers/assets/69306070/c79ea85b-bcf0-4006-8cc7-8f4606b12d23)
