### ISSUE TITLE
[NEWS] Previous issues to be listed on the website

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/writers#42]
Why: suggested by Asim in the loom video he created about newsletter OKRs
When: this task is for next year as Osama is on leave already. Blocked / on hold for now
What: find a way to add previous newsletter issues to the website 
We could use [this view](https://us5.campaign-archive.com/home/?u=ddc99c7db248c3df0ef4f7d24&id=c5376a805c).
To be discussed when we are back next year.

**Comment by zanete** [comment]
@jawache @NAMRATA-WOKE - cleaning up the web board and would like to know if it's still a good idea to figure out a way to integrate previous newsletter issues into the website in some view?
* If yes, we can set up a quick call to discuss a couple of options
* * Iframing if we just want a simple adidtional page that looks like this https://us5.campaign-archive.com/home/?u=ddc99c7db248c3df0ef4f7d24&id=c5376a805c
* * using the API to grab previous latest newsletters and displaying them in a nice styled list
* If not, then I will just remove this from the board and forget about it
