### ISSUE TITLE
Images for article: Accenture SCI Case Study

### ISSUE THREAD

**Issue by Jenya-design** [Green-Software-Foundation/writers#54]
Why: 2 images are requested for [this article](https://docs.google.com/document/d/12WUmSgokfbbqffbkPGGqDz_kt5iu978Z/edit) 
What: 
1. redo attached image 
2. cover image 

![Image](https://user-images.githubusercontent.com/69306070/219389868-e24b2bd3-86ff-4546-adef-caf4fb2d2c62.png)

**Comment by zanete** [comment]
@Jenya-design thanks again, I wasn't sure who requested this from you and how it got onto your place. 
Now I understand that it's for the Articles project, hopefully there will be a dedicated PM for it soon who could benefit from a tag like that jut to know what's going on and who's involved in the project. 

For now (as of this week) I have taken on the role to facilitate some of the management of that project until a new PM joins, and with that said, until further notice, you can tag me if for any reason you are still needing to add these kinds of issues yourself, but I hope to have a process where it is created for you. Does this help clarify the situation?

cc @NAMRATA-WOKE @ursvill @jawache

**Comment by Jenya-design** [comment]
Thank you @zanete 
Sure, I'll tag you in all similar issues
