### ISSUE TITLE
[Article] Reflection: Would you pay more for cloud computing if it was net-zero and powered 24/7 by 100% carbon free energy?

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/writers#69]
## Article Details
_Please enter the details here_

**Proposer**: Namrata Narayan | Communications Lead | @NAMRATA-WOKE)
**Abstract**: This blog will explore the results of an [online poll](https://www.linkedin.com/feed/update/urn:li:activity:7038586924457971713/) conducted by Asim Hussain, the Executive Director and Chairperson of The Green Software Foundation. The poll asked whether technologists would pay more for cloud computing if it was net-zero (as per SBTi) and powered 24/7 by 100% carbon-free energy and how much more they'd be willing to spend. The blog can analyze the results and provide insights into what the results might signal for new solution providers and institutional leadership. 
**Why**: The poll generated a lot of interest on LinkedIn and we want to build off that momentum to engage the public in topical conversations about green software to scale the movement. 
**Audience**: CTOs/ CIOs/ Heads of Software Sustainability, Product Managers 
**Timeline**: Once the poll closes, sometime between March 20-24. 

## Important Information
_To be filled out later_

**Author**: (Who is assigned to write this article)
**Other contributors**: (Experts, Reviewers)
**Article Link**: (Link to the doc, must be in our official GSF drive)
**Graphics Link**: (Link to the design assets for this article, must be in our official GSF drive)
**Published Link**: (The link the article was published to for memory)

## Checklist
- [x] Idea discussed and selected for writing. _After checking this box, set Status to "Todo" under "Articles" project_
- [x] Author identified. _After checking this box Assign issue to the Author_
- [x] Google doc link created in GSF drive. 
- [x] In progress. _After checking this box, set Status to "In Progress" under "Articles" project_
- [ ] Draft created. _After checking this box, set Status to "In Review" under "Articles" project. Assign issue to Reviewer/Author during the back-and-forth_
- [ ] Draft reviewed. _After checking this box, set Status to "In Publishing" under "Articles" project. Assign issue to Graphic Designer and add "Graphic Design" to issue's Projects_
- [x] Graphics created. _After checking this box, assign to TBC for approval._
- [ ] Approved. _After checking this box, assign to TBC for publishing._
- [ ] Published. After checking this box, set Status to "Ready" under "Articles" project. Assign to Marketing and add "D: Marketing" to issue's Projects
- [ ] Shared on socials
- [ ] Shared on newsletter. After checking this box, set Status to "Done" under "Articles" project and close issue.

**Comment by jawache** [comment]
Notes from writers call.
- Perhaps write a first draft from the poll.
- Have Tamara review and add her thoughts on top.

**Comment by NAMRATA-WOKE** [comment]
WIP -- need help @jawache. Particularly want feedback on:
- angle of the article (e.g. business case)
- what GSF tools/resources we can highlight here, keeping in mind the target audience is cloud computing providers 
- what do we want people to do immediately after reading this article? 

### Cloud Computing: The Business Case for 100% Carbon-Free Energy

The cloud computing industry is growing at an unprecedented pace. With businesses and consumers relying on cloud services for everything from data storage to application hosting, the demand for cloud computing solutions will only increase. However, with this growth comes environmental harm: increased carbon emissions. The cloud already [emits](https://www.climatiq.io/blog/measure-greenhouse-gas-emissions-carbon-data-centres-cloud-computing) more global GHG emissions than the commercial airline industry, surpassing those generated by over 22.2 million flights annually. No one can argue that the industry now must mitigate the carbon emissions of software with intelligent climate-conscious code that uses greener energy sources with increased efficiency.

According to a recent poll conducted by Asim Hussain, the Executive Director of the Green Software Foundation, 72% of respondents said they would be willing to pay more for cloud computing services powered by 100% carbon-free energy. Specifically, 23% said they would pay 5% more, 28% would pay 10% more, and 18% would pay 25% more.

**So, there might be a strong business case for cloud providers to be 100% carbon-free.** By transitioning to 100% carbon-free energy to power their cloud environments, they can reduce their carbon footprint and expand their serviceable market. Tapping into the growing demand for sustainable solutions will also help their corporate commitments to environmental targets set and provide greater competitive advantage over companies that are not taking steps to reduce their carbon emissions.

The Green Software Foundation is here to help cloud computing providers transition to 100% carbon-free energy. The foundation offers a range of resources and tools, including [SCI] and [Carbon Aware API]?  

We recognize transitioning to 100% carbon-free energy comes with challenges. We've learned this past year that one of the biggest obstacles for cloud computing solution providers is that renewable energy sources can be less reliable and more expensive than traditional fossil fuel sources. Some providers have also expressed needing help securing renewable energy contracts or upgrading their infrastructure to support renewable energy sources. 

Luckily, there are resources and tools to help cloud providers improve their energy practices and transition toward cleaner sources. For example, [The MATCH Model](https://github.com/pencleanenergy/MATCH-model) is an energy procurement planning model that identifies the lowest-cost portfolio of clean and /or renewable energy contracts for annual, time-coincident, and /or emissions-optimized energy procurement goals.

**Comment by zanete** [comment]
Capturing status of weekly check-in:
-  check in with XXX on whether there are any relevant insights from SOGS that could be added
- @NAMRATA-WOKE create a google doc for collaborating on the draft in https://drive.google.com/drive/folders/1PWHCCvGyu4i7S-KIVBA98m5gnidCZRGd and share the link

**Comment by NAMRATA-WOKE** [comment]
https://docs.google.com/document/d/1zpTdcXQwYwi-ZfFeTAENSXPX9gXa6o8UeQcOeG2q4lc/edit?usp=sharing

**Comment by zanete** [comment]
Weekly call status:
- in progress, aiming to publich next week before newsletter
- @NAMRATA-WOKE to reach out to  @Jenya-design  to get cover art for this ahead of time
- @jawache might or might not have a chance to review, go ahead without his review

**Comment by zanete** [comment]
@Jenya-design a heads up that there will be a task for Graphic Design for this article that's supposed to be published this week, so I have added to the Graphic design board. @NAMRATA-WOKE let me know if anything's changed and it's no longer going ahead this week.
@jawache did not get a chance to review and is not in this week, so please go ahead without his review.

**Comment by Jenya-design** [comment]
@zanete I think the image for this article is already created, please check the issue #96
