### ISSUE TITLE
[Article] Insights and Takeways from GSF's inaugural Meetup in London

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/writers#85]
## Article Details
_Please enter the details here_

**Proposer**: Namrata Narayan | Communications Lead, GSF | @NAMRATA-WOKE 
**Abstract**: A brief 500 word article that summarizes highlights from GSF's inaugural Meetup in London, sharing key takeways and insights from panelists and attendees. 
**Why**: By sharing insights, GSF demonstrates its commitment to inform its stakeholders about the organization's activities and progress. More importantly, sharing positive experiences from the Meetup can motivate others to organize GSF Meetups, helping build momentum.
**Audience**: Software practitioners, particularly developers 
**Timeline**: March 27, 2023

## Important Information
_To be filled out later_

**Author**: (Who is assigned to write this article)
**Other contributors**: (Experts, Reviewers)
**Article Link**: (Link to the doc, must be in our official GSF drive)
**Graphics Link**: (Link to the design assets for this article, must be in our official GSF drive)
**Published Link**: (The link the article was published to for memory)

## Checklist
- [x] Idea discussed and selected for writing. _After checking this box, set Status to "Todo" under "Articles" project_
- [x] Author identified. _After checking this box Assign issue to the Author_
- [x] Google doc link created in GSF drive. 
- [x] In progress. _After checking this box, set Status to "In Progress" under "Articles" project_
- [x] Draft created. _After checking this box, set Status to "In Review" under "Articles" project. Assign issue to Reviewer/Author during the back-and-forth_
- [x] Draft reviewed. _After checking this box, set Status to "In Publishing" under "Articles" project. Assign issue to Graphic Designer and add "Graphic Design" to issue's Projects_
- [x] Graphics created. _After checking this box, assign to TBC for approval._
- [x] Approved. _After checking this box, assign to TBC for publishing._
- [ ] Published. After checking this box, set Status to "Ready" under "Articles" project. Assign to Marketing and add "D: Marketing" to issue's Projects
- [ ] Shared on socials
- [ ] Shared on newsletter. After checking this box, set Status to "Done" under "Articles" project and close issue.

**Comment by NAMRATA-WOKE** [comment]
@ursvill would you be interested in writing this?

**Comment by ursvill** [comment]
sure, are we talking about the meetup event last year?

**Comment by NAMRATA-WOKE** [comment]
No the one coming up on Thursday @ursvill 

https://www.meetup.com/gsf-london/events/292217696/

**Comment by ursvill** [comment]
I am away on vacation, returning sat. if it has to be done before next week, then it’s a no for me.

**Comment by zanete** [comment]
Capturing the status on weekly check-in
- @NAMRATA-WOKE to reach out to @tadanna  for intros with organisers for details and photos

**Comment by tadanna** [comment]
@NAMRATA-WOKE let me know exactly what you need here. mostly 3 people worked hard to make this happen and of course Asim helped a lot!

**Comment by Jenya-design** [comment]
Yes @NAMRATA-WOKE I'll prepare the image by 13:00 London
@Stephaniestocker please let me know if you need it earlier

**Comment by NAMRATA-WOKE** [comment]
Thank you @Jenya-design! Appreciate you accommodating the quick turnaround.

**Comment by Stephaniestocker** [comment]
That’s ok- thank you Jenya!!

**Comment by NAMRATA-WOKE** [comment]
Looks good to me! Thanks @Jenya-design!

**Comment by Stephaniestocker** [comment]
Published all :)
