### ISSUE TITLE
[Use Case]: Measuring emissions for a large three tier, on-premise software system

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/writers#90]
## Article Details
SCI Case Study

**Proposer**:  Gadhu Sundaram | NTT Data | GitHub U/N: GadhuNTTDATA)
**Abstract**:  This article describes how NTT DATA used the SCI score to help measure the carbon footprint of a large scale three-tier on premise software system
**Why**: SCI Use Case
**Audience**: 
**Timeline**: No constraints

## Executive Summary 
 This article describes how NTT DATA used the SCI score to help measure the carbon footprint of a large scale three-tier on premise software system

### Description of problem 
There are a number of large scale multi tier, on-premise software systems being developed and maintained by NTT DATA that run enterprise scale applications such as ecommerce. While there is a desire by all enterprises to migrate to the cloud at some point in the future, there will be a considerable portfolio of on-premise solutions that we need to live with for the next few years. It is important that the carbon footprint of these applications are measured and optimised, especially as they continue to scale.

### How the use case solves the problem
NTT DATA has a mature set of tools and techniques to optimise performance of such software systems. We use industry standard benchmarks such as TPC-W which provide a benchmark for performance in terms of Web Interactions per second for a given load.  We have implemented tooling across the entire stack including networking, hardware and software to measure the rate of emissions using SCI. We have measured it in term of co2 equivalent per web interaction

### Main benefits of the solution
This has helped us to gather carbon emissions related metrics , utilising some of the mature processes that we regularly perform such as the performance optimisation. This in turn helps us understand the impact of scaling the systems on the total carbon footprint and take appropriate actions to help bring down the carbon footprint

### What was the outcome, how were carbon emissions reduced
We now have a baseline for the carbon impact per unit of work , based on a blueprint infrastructure, that provides a baseline performance. We will now use this to implement patterns that decrease the carbon footprint with no negative impact on performance and also to be aware of the carbon impact on any performance improvement, scaling decision that we make on the software system

## Important Information
_To be filled out later_

**Author**: (Who is assigned to write this article)
**Other contributors**: (Experts, Reviewers)
**Article Link**: (Link to the doc, must be in our official GSF drive)
**Graphics Link**: (Link to the design assets for this article, must be in our official GSF drive)
**Published Link**: (The link the article was published to for memory)

## Checklist
- [x] Idea discussed and selected for writing. _After checking this box, set Status to "Todo" under "Articles" project_
- [x] Author identified. _After checking this box Assign issue to the Author_
- [x] Schedule 
- [x] Google doc link created in GSF drive. 
- [x] In progress. _After checking this box, set Status to "In Progress" under "Articles" project_
- [x] Draft created. _After checking this box, set Status to "In Review" under "Articles" project. Assign issue to Reviewer/Author during the back-and-forth_
- [x] Draft reviewed. _After checking this box, set Status to "In Publishing" under "Articles" project. Assign issue to Graphic Designer and add "Graphic Design" to issue's Projects_
- [x] Graphics created. _After checking this box, assign to TBC for approval._
- [x] Approved. _After checking this box, assign to TBC for publishing._
- [x] Published. After checking this box, set Status to "Ready" under "Articles" project. Assign to Marketing and add "D: Marketing" to issue's Projects
- [ ] Shared on socials
- [ ] Shared on newsletter. After checking this box, set Status to "Done" under "Articles" project and close issue.

**Comment by seanmcilroy29** [comment]
@ursvill  - Could you please reach out to @gadhuNTTDATA  with an update? He has been inquiring about it.

**Comment by ursvill** [comment]
Henry at WattTime: @GadhuNTTDATA , would you be interested in expanding this into an article like this? https://greensoftware.foundation/articles/how-accenture-implemented-the-sci-specification-score-to-track-software-emissions

**Comment by ursvill** [comment]
https://docs.google.com/document/d/1V3XXpu8NghS_rMLSgp7KaVUJC1mnltRT

**Comment by ursvill** [comment]
@Jenya-design - can you add some color to this, please : )

**Comment by Jenya-design** [comment]
Thank you @ursvill, please let me know what's my deadline

**Comment by ursvill** [comment]
publish date is May 8, so May 7 would be great @Jenya-design

**Comment by ursvill** [comment]
@Henry-WattTime - I was talking to Gadhu on Slack and he would love to expand the case into something like the Accenture article. I have uploaded his paper here: https://docs.google.com/document/d/1V3XXpu8NghS_rMLSgp7KaVUJC1mnltRT
Are you ok working with Gadhu directly on this doc on Google drive?

**Comment by zanete** [comment]
@ursvill please try Henry via email

**Comment by Jenya-design** [comment]
Hello @ursvill 
Please review the image attached or saved on [GSF Drive here](https://drive.google.com/drive/folders/1i0urjHEJ94jGxixyPPXfCYkxE2q0hTAw?usp=share_link)
I'll be away May 5-8, please let me know if you need adjustments done before I go
Thank you!

![EnergyConsumptionOnPromiseEcommerce-GreenSoftwareFoundation1](https://user-images.githubusercontent.com/69306070/235931714-861b3e86-753d-47ad-98b5-048e86f95093.png)

**Comment by ursvill** [comment]
THX @Jenya-design

**Comment by zanete** [comment]
@seanmcilroy29 please email for review to the Standard WG, with chairs to Approve: https://docs.google.com/document/d/1V3XXpu8NghS_rMLSgp7KaVUJC1mnltRT

**Comment by seanmcilroy29** [comment]
Article under Standards WG [R&A review](https://github.com/Green-Software-Foundation/sci-guide/issues/45)
Article will be published if no comments are submitted by 17 May.

**Comment by zanete** [comment]
double- checking that this has been or will be copy-edited? @ursvill 
FYI @NAMRATA-WOKE @jawache

**Comment by ursvill** [comment]
Yes, @NAMRATA-WOKE did a review, but I am happy to look through it as well

**Comment by zanete** [comment]
@seanmcilroy29 can you confirm that your comment here https://github.com/Green-Software-Foundation/writers/issues/91#issuecomment-1551733600 refers to this issue?
And also, that link no longer works, was it unpublished?
cc @ursvill @NAMRATA-WOKE @jawache

**Comment by seanmcilroy29** [comment]
@zanete - The article was unpublished, so both don't go out at the same time and will be published on the 25th

**Comment by NAMRATA-WOKE** [comment]
Will be published on the 26th by @seanmcilroy29

**Comment by NAMRATA-WOKE** [comment]
@ursvill take what's on GitHub for the actual case study and structuring it to be included in the article that's published -- will try and message @NAMRATA-WOKE if any issues come up! 

@jawache: This is a technical paper. Learnings might be buried in the text, which need to be raised to the forefront. @ursvill reach out to Catherine to see how she might be able to rewrite it to make it easier to understand.

**Comment by ursvill** [comment]
Hi Gadhu

We just had a brief discussion on the below use case that is published on the GSF website. While it’s a great use case, I feel we could add a bit more substance to the article and make it more valuable to the reader.

Would you be willing to look through it again and make a few changes?

E.g.
Can you elaborate more on the learnings and key takeaways
Can you include some of the material from GitHub, a few examples of the calculations, i.e.:
How were emissions saved (last par.)
Example calculation for par. “How the use case solved the problem”

Hope this will work

**Comment by NAMRATA-WOKE** [comment]
@ursvill is waiting on Gadhu's response. @NAMRATA-WOKE and Urs decided that any simplification or narrative-setting will be taken care of by the two of us.

**Comment by NAMRATA-WOKE** [comment]
@ursvill will reach out one last time and then let it go!

**Comment by ursvill** [comment]
reached out; will follow up once more in a few days

**Comment by NAMRATA-WOKE** [comment]
Gadhu responded. He needs more time (assuming 1-2 weeks). @ursvill will follow-up in a couple of weeks.

**Comment by NAMRATA-WOKE** [comment]
We're letting this one go --  too much manual effort.
