### ISSUE TITLE
Create Image for Carbon Free Article

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/writers#96]
What: Need an image for an upcoming [blog article](https://docs.google.com/document/d/1zpTdcXQwYwi-ZfFeTAENSXPX9gXa6o8UeQcOeG2q4lc/edit?usp=sharing).
Why: Support promotion and presentation of article. 

Image can either be a rendition of the poll conducted on LinkedIn or expression of "carbon free cloud computing" (i.e., cloud that is powered only by renewable energy like wind, solar and hydro). 

Article is scheduled to be published on April 10th.

**Comment by Jenya-design** [comment]
Hello @NAMRATA-WOKE 
Please check two images for the article attached and [on Drive](https://drive.google.com/drive/folders/1Rbz0aWTEsrl4cUkU1z5o7bjlQPwrsXyd?usp=share_link)


![Image](https://user-images.githubusercontent.com/69306070/230658610-ffebe6ce-6863-4af8-865a-577889de26c9.png)



![Image](https://user-images.githubusercontent.com/69306070/230658622-24c65b7f-17c1-4882-b5ab-6ffd479c1e6a.png)

**Comment by NAMRATA-WOKE** [comment]
@Jenya-design love em, thank you!
