### ISSUE TITLE
Guidelines: Contributor Writing Program

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/writers#99]
What: Information and guidelines to share publicly with practitioners interested in building their thought leadership on green software and leveraging the GSF network and platform to reach a targeted and global audience. 
Why: People need to have a clear understanding of what they are allowed and encouraged to submit to the foundation to increase their chances of getting their articles published. The more they don't know, the more frictious the experience will be and it will discourage people from creating content for the foundation.
When: As soon as possible. 

[This document ](https://docs.google.com/document/d/1bCbDh9a6vzH6Jcq5lgLJCUl6fyjY0Mn5kX2XkczYapU/edit#)will change as we learn and gather feedback from people who are contributing. Not set in stone.

**Comment by NAMRATA-WOKE** [comment]
@jawache We can be choosy about topics/ themes.

**Comment by ursvill** [comment]
looks ok to me!

**Comment by adamj89** [comment]
- [ ] @NAMRATA-WOKE to look into access for GSF members

**Comment by zanete** [comment]
@jawache @NAMRATA-WOKE I never have updated any .md files, was this approved and should this task be done?

**Comment by NAMRATA-WOKE** [comment]
This has launched!
